### ISSUE TITLE
Estructurar en una tabla los proyectos en desarrollo

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/terremoto-cdmx#102]
En la sección de "Otros proyectos desarrollándose", es difícil de leer como bullets. Ya había una tabla creada con la información (repositorio, descripción, stack y canal) de cada proyecto. Además, el título debe invitar a que las personas se sumen a contribuir a esos proyectos.

**Comment by tlacoyodefrijol** [comment]
Sugieres ponerlo como el de grupos de trabajo?

**Comment by miguelsalazar** [comment]
Sí. De tal forma que podamos canalizar a las personas de manera más eficiente.
Buscamos la siguiente estructura:

> **¿Cómo ayudar?**
> 
> - Súmate a un proyecto
> - Únete a un grupo de trabajo

Y cada uno con un link a su respectiva sección.

**Comment by tlacoyodefrijol** [comment]
Ponemos help wanted o te lo echas tú @miguelsalazar ?

**Comment by miguelsalazar** [comment]
Ya lo trae @tugaarredondo :)
