### ISSUE TITLE
Agregar links de navbar

### ISSUE THREAD

**Issue by tlacoyodefrijol** [CodeandoMexico/terremoto-cdmx#108]

**Comment by tlacoyodefrijol** [comment]
Ya intenté normal con  `<A href="#section-1">Section One</A>`y no funciona, estoy pensando en usar relative links https://github.com/benbalter/jekyll-relative-links

**Comment by tlacoyodefrijol** [comment]
También intenté agregarlo con liquid y nada

**Comment by juanjcsr** [comment]
Lo puedo checar yo. Se pueden generar los links agregando ID a las secciones y creando el link via el href

**Comment by Crowly34** [comment]
@tlacoyodefrijol Agregalos como ligas de markdown `[Quiero ayudar](#quiero_ayudar)` para este caso tienes que agregar un id en index `<section id="{{ id }}" class="smx-{{ id }}">` y entonces ese boton te manda a la seccion de quiero ayudar

**Comment by tlacoyodefrijol** [comment]
@juanjcsr assigned

**Comment by Crowly34** [comment]
@juanjcsr usa markdown, queda bien y según yo puedes usar html dentro de []

**Comment by juanjcsr** [comment]
Voy, lo checo :)

**Comment by juanjcsr** [comment]
@Crowly34 Para el Navbar los estoy agregando via IDS, dado que el navbar no tiene markdown. Abro el PR #115.

Hacen falta algunas secciones del Navbar que no se encuentran en el sitio (Agradecimientos, Contacto, Necesito Ayuda, etc). ¿Qué se va a hacer con estas?

**Comment by Crowly34** [comment]
@tlacoyodefrijol cierro este issue? ya se entregó

**Comment by tlacoyodefrijol** [comment]
@Crowly34 se entregó parcialmente. Voy a agregar los links que faltan
