### ISSUE TITLE
Cambiar la fuente de Google Fonts a una Websafe

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#110]
Cambiar Fuente de Roboto mono por Helvetica y eliminar la liga del proyecto

**Comment by HzJavier** [comment]
Estoy trabajando en este

**Comment by Crowly34** [comment]
asignee: @HzJavier

**Comment by tlacoyodefrijol** [comment]
@HzJavier te mandé el invite al equipo
