### ISSUE TITLE
Agregar Footer

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#111]
Agregar el footer de acuerdo con el [diseño](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01)

**Comment by coderdiaz** [comment]
Voy a trabajar en este 👍

**Comment by Aliuzha** [comment]
ya lo termine :( pero no se como entregarlo

**Comment by coderdiaz** [comment]
@Aliuzha solo tienes que subir la rama en que lo trabajaste y hacer el PR correspondiente 👍

**Comment by coderdiaz** [comment]
Este issue está siendo trabajo por @Aliuzha

**Comment by Aliuzha** [comment]
@coderdiaz COmo me lo puedo asignar? soy nuevo en esta herramienta

**Comment by coderdiaz** [comment]
@Aliuzha solo pueden asignarse aquellos que están como colaboradores en el repositorio, hay que solicitar el permiso en el canal de slack de desarrollo para que te agreguen los owners de los repositorios

**Comment by tlacoyodefrijol** [comment]
@Aliuzha no necesitas tenerlo asignado, aunque ya te mandé la invitación al equipo del repo. 

Lo que mencionó @coderdiaz es lo que puedes encontrar a continuación, para [hacer un Pull Request](https://stackoverflow.com/questions/10364429/how-to-commit-to-remote-git-repository#10364506)

**Comment by Crowly34** [comment]
@Aliuzha si no eres colaborador del proyecto, necesitas hacer fork del mismo, y clonar el fork que tienes en tu github, después de eso haces un PR de tu fork a master, si no eres colaborador no puedes hacer rama en el proyecto original por lo que asi es como lo vas a subir.

**Comment by Aliuzha** [comment]
Hice un cambio en index.html para incluir los font-awesome icons que estan en el requerimiento
Hice el footer.md

**Comment by Aliuzha** [comment]
![image](https://user-images.githubusercontent.com/9615172/30720582-b5be80b8-9eed-11e7-9328-649f2658295f.png)
