### ISSUE TITLE
Franja rosa al término de cada sección

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#113]
Agregar una franja rosa como la de al final de la seccion "necesito ayuda" en el diseño, cambiar las imagenes de las demás secciones por esta franja.

[Acá diseño](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01)

**Comment by ghost** [comment]
En proceso :)

**Comment by xiam** [comment]
@evillasr, @coderdiaz quien queda responsable de resolver el issue?

**Comment by coderdiaz** [comment]
@xiam Creo que lo esta trabajando @evillasr

**Comment by anahiruiz** [comment]
Oigan ya tengo la franja, la necesitan?, habría conflicto con algún otro commit?
![captura de pantalla de 2017-09-22 16-48-13](https://user-images.githubusercontent.com/13294599/30765552-dac6118c-9fb5-11e7-9f85-6c4061d38d23.png)
