### ISSUE TITLE
Detallar la informacion de la situacion interna de los grupos "Topos"

### ISSUE THREAD

**Issue by mxcoder** [CodeandoMexico/terremoto-cdmx#114]
Hay distintos grupos "Topos de Tlatelolco" y parece que no se llevan nada bien, PERO, creo que aun asi los grupos estan apoyando en distintos lugares.

Seria bueno que incluyeramos un disclaimer en la parte de donaciones.

**Comment by Ritalina** [comment]
Ya pusieron esta nota en la p[agina, para explicar eso. http://www.animalpolitico.com/2017/09/grupos-topos-donaciones/ :)

**Comment by miguelsalazar** [comment]
¿El artículo de @Ritalina resuelve tu duda, @mxcoder ?

**Comment by mxcoder** [comment]
@miguelsalazar si, no es para mi, pero supusimos que sera una duda comun ente la gente que vaya a la seccion de donaciones. Creo que es el articulo mas completo no?

**Comment by Ritalina** [comment]
Sí. Entonces cerraré el issue. Para que se preste atención a otros puntos. :)
