### ISSUE TITLE
Crear páginas individuales para concentrar información por entidad afectada

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#12]

**Comment by fmicalizzi** [comment]
Creo que podríamos hacer un solo page simulando tweetdeck con los hashtags mas relevantes.

**Comment by darredondort** [comment]
Hola @xiam definitivamente hace falta más información y formas de canalizar ayuda a Morelos y Puebla.

Wikipolítica, r3d, Horizontal y otras organizaciones se movilizaron para generar centros de acopio específicos **para Morelos**:
https://twitter.com/WikipoliticaCMX/status/910544616176234496
![dklnbykuiaa6stx](https://user-images.githubusercontent.com/6744123/30657092-f509ba96-9dfb-11e7-9fdd-8f8f4ad3ddac.jpg)

**Comment by miguelsalazar** [comment]
@xiam sigues trabajando en este issue?

**Comment by xiam** [comment]
Sí, parece que Angie Navarro, en el canal, puede ayudarnos con datasets que necesitamos y nos evitaría hacerlo a mano. Sigo conversando...

**Comment by nitzwalsh** [comment]
¿Cómo se están populando los datos de los mapas en sismomexico.org? Quiero agregar los centros de acopio en Aguascalientes.

**Comment by Maurissalgado** [comment]
Como puedo ayudar con diseño?

**Comment by tlacoyodefrijol** [comment]
@xiam hay update de este?

**Comment by xiam** [comment]
No @tlacoyodefrijol, probablemente convenga cerrarlo hasta que dejemos de mover la estructura del sitio, tengamos los datos en algún lado y podamos hacer cambios tan grandes. Lo cierro por ahora.
