### ISSUE TITLE
Cambiar boton de necesito ayuda

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#123]
El botón "necesito ayudar" debería decir "necesito ayuda" en la seccion rosa con dos botones 

[Diseño](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01)

**Comment by astrocumbia** [comment]
Listo, https://github.com/CodeandoMexico/terremoto-cdmx/pull/129

**Comment by coderdiaz** [comment]
@positr0nix Excelente, gracias 👍
