### ISSUE TITLE
política de privacidad (de datos)

### ISSUE THREAD

**Issue by defvol** [CodeandoMexico/terremoto-cdmx#124]
Parecería irrelevante en la emergencia, pero definir una política de privacidad base, nos serviría para:

- delinear las expectativas del uso de información que estamos recopilando
- registrar servicios o apps a APIs de redes sociales
- exigir la protección de datos personales en los desarrollos y trabajos de nuestra comunidad

Usemos este thread para delinear y generar un borrador de lo que sería un template de privacidad acorde a los valores de la comunidad.

**Comment by miguelsalazar** [comment]
¿Podemos draftearla en un documento colaborativo?

**Comment by defvol** [comment]
Buena idea! acá un piratepad: http://piratepad.net/Z5GK7DAYTE
Empecemos...

**Comment by defvol** [comment]
Buena referencia de Mozilla acá: https://developer.mozilla.org/en-US/Marketplace/Publishing/Policies_and_Guidelines/Privacy_policies
