### ISSUE TITLE
Cambiar texto de botones

### ISSUE THREAD

**Issue by salmedina** [CodeandoMexico/terremoto-cdmx#127]
En lugar de usar el verbo "Cargar" como en "Cargar Mapeo" debería ser "Mostrar Mapeo". Es más intuitivo y natural para alguien que no está relacionado al cómputo.

**Comment by javierojeda94** [comment]
Lo estoy resolviendo!

**Comment by javierojeda94** [comment]
Este creo que ya está resuelto. Se puede hacer merge?

**Comment by ghost** [comment]
Sí, ya está listo

**Comment by gabelula** [comment]
Pronto.
