### ISSUE TITLE
donde se fueron los links?

### ISSUE THREAD

**Issue by gabelula** [CodeandoMexico/terremoto-cdmx#128]
Desaparecieron los enlaces con el último rediseño. Las URL son texto plano en el sitio. Hay que vovler a poner enlaces. 

https://github.com/carwin/markdown-styleguide

**Comment by astrocumbia** [comment]
De qué sección?

**Comment by marianagh** [comment]
Creo que se refiere a las de la navegación.

**Comment by javierojeda94** [comment]
Yo me hago cargo, revisaré todo y cualquier duda se las hago saber

**Comment by javierojeda94** [comment]
Alguien tiene más info sobre este issue? No logro reproducirlo

**Comment by gabelula** [comment]
- En el footer faltan algunos links.
- hay un par de URLs que podrian ser convertidas a links

**Comment by javierojeda94** [comment]
On it

**Comment by ghost** [comment]
¿Cómo va?

**Comment by javierojeda94** [comment]
listo, ya hice el PR https://github.com/CodeandoMexico/terremoto-cdmx/pull/151

**Comment by javierojeda94** [comment]
Algunos links todavía no aparecen porque las secciones todavía no existen aún... Hay que ver cómo se va a poner y las voy agregando
