### ISSUE TITLE
Proveer alguna manera de conectar necesidades con personas

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#13]
Por ejemplo, hay gente que necesita transporte para traslado de víveres y gente que puede poner sus autos o bicis.

**Comment by josuesfakee** [comment]
podemos usar un documento de google docs como la que tienen en la vista principal.
alguien que me de el visto bueno para pedir ayuda a todos mis amigos y conocidos.
- SALUDOS!

**Comment by miguelsalazar** [comment]
Creo que valdría la pena explorar si ya hay esfuerzos de este tipo, antes de empezar uno nosotros.

**Comment by josuesfakee** [comment]
me parece perfecto, haré una búsqueda para ver si alguien tiene un recurso de esto. 
Si ustedes encuentran algo, avísenme, si no, para nosotros crearlo de la manera mas rápida

**Comment by josuesfakee** [comment]
Hola a todos, ya estuve buscando algún recurso con información acerca de lo que necesitamos y no encontré nada, creo que es momento de nosotros crear este y debe ser filtrado por estado.

**Comment by miguelsalazar** [comment]
Sería bueno coordinar esto con el equipo de `#sismomx-realtime` dentro de Slack.

**Comment by paulinabustos** [comment]
@xiam Estamos trabajando en eso en este issue: https://github.com/CodeandoMexico/terremoto-cdmx/issues/20

**Comment by xiam** [comment]
Otro esfuerzo por acá https://docs.google.com/spreadsheets/d/1qiJg4dIPmxbfmIbq1NtXGPm5lwwDZlWTwKacyl5vtUs/edit#gid=0

**Comment by josuesfakee** [comment]
yo puedo ayudar a ingresar mas información a ese documento, por favor compártelo conmigo.

**Comment by S41nz** [comment]
Acá ya levantaron una desde ayer, si prefieren agregen la liga:

https://docs.google.com/forms/d/e/1FAIpQLSe3Zo51MC-luRZeR-oUDIpnUb8LiTnGt6l_xJlFFZWMInLwVg/viewform

**Comment by josuesfakee** [comment]
esta perfecta la información que contiene el documento, lo que tendríamos que hacer es facilitar la información mas reciente a los usuarios y personas para que vayan a apoyar, así como también el dar de baja la información cuando se cumpla el punto.

**Comment by almarosabenitez** [comment]
Hola a todos. También está este link: https://docs.google.com/spreadsheets/d/1mo9czjIQupWSkjyM--_RSusShy-WbHi8w28oBmxeufk/htmlview

**Comment by miguelsalazar** [comment]
Revisar #20 y el canal de `#sismomx-realtime` en Slack.
