### ISSUE TITLE
Hacer un buscador con JSONS de la API de Sheets

### ISSUE THREAD

**Issue by martiuh** [CodeandoMexico/terremoto-cdmx#130]
Me metí a la página y se me hizo que podría quedar muy bien una especie de buscador, para acceder a información rápida de personas (desaparecidas, encontradas o fallecidas), mascotas, etc. 
El único inconveniente es si no alcanzaríamos los límites de la API que son 500 requests per 100 seconds per project, and 100 requests per 100 seconds per user.

**Comment by NotZombieFood** [comment]
@martiuh ya la andas haciendo o te puedo apoyar?

**Comment by martiuh** [comment]
@NotZombieFood  hola, apenas la ando haciendo. Ya hice pruebas con la API de Google y puedo conseguir los JSON de las hojas del libro. Cómo no podemos comunicar? soy nuevo aquí en codeando

**Comment by NotZombieFood** [comment]
@martiuh estoy en el Slack como gcruz, podemos hablar por allá

**Comment by NotZombieFood** [comment]
https://github.com/NotZombieFood/sismoMX-SearchAPI
