### ISSUE TITLE
Sección de FAQs

### ISSUE THREAD

**Issue by marianagh** [CodeandoMexico/terremoto-cdmx#136]
[Disegno](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01)

**Comment by javierojeda94** [comment]
ya está resuelto este issue?

**Comment by marianagh** [comment]
Esta resuelto en un PR.

**Comment by almarngl** [comment]
Ya lo vi @marianagh, sorry por cerrarlo. Pero me indica que tiene conflictos.
