### ISSUE TITLE
Seccion Quiero ayudar

### ISSUE THREAD

**Issue by marianagh** [CodeandoMexico/terremoto-cdmx#138]
[`https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01`](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01)

**Comment by HzJavier** [comment]
@marianagh que pasó con estos issues?

**Comment by marianagh** [comment]
Este alguien lo incluyo en otro issue. Lo cerré porque lo creamos al mismo tiempo. #135
