### ISSUE TITLE
Verificador de estructuras de inmuebles

### ISSUE THREAD

**Issue by ricardomeza** [CodeandoMexico/terremoto-cdmx#139]
**Verificador de estructuras de inmuebles**

Sitio Web/App para verificar que las construcciones para uso habitacional o comercial tengan las condiciones, certificaciones, validaciones y cualquier información que ayude a verificar que es una construcción con más probabilidades de resistir sismos con intensidad peligrosa, como los de 1985 o 2017.

Todos los trabajos serán realizados por la sociedad civil para evitar contaminación política y/o de dueños de empresas que deseen ocultar o cambiar información.

Los datos de cada estructura debe ser presentados en una tarjeta/pagina con los detalles de validaciones:
1. Coordenadas latitud y longitud para su localización en un mapa digital con la capacidad de navegación, zoom in/out y otras características que, al recibir un clic lleve a su tarjeta/página
2. Datos de domicilio/dirección
3. Nombre de arquitecto/empresa constructora y datos de contacto
4. Características de la estructura que la identifiquen como segura o insegura que incluirán fotografías
5. Foto de fachada
6. Nombre del profesional que realizó la visita y revisión
7. La privacidad de los propietarios tendrá prioridad uno

Cada estructura recibirá una calificación que será determinada por los expertos en el tema, para evitar complejidad de cálculos, se pueden tener solo tres valores: segura, en riesgo o insegura

El Homepage tendrá un dashboard de la calificación promedio de todas las estructuras registradas y otros datos que serán determinados por los expertos para ofrecer información resumida.

También tendrá un buscador para localizar las estructuras ya sea por domicilio, nombre de edificación o razón social, pero no de nombres de personas físicas y el resultado de la búsqueda se presentará en un mapa digital bajo el cuadro de búsqueda con opción para ver el resultado en el mapa o en tarjetas.

Solicitud y registro de la revisión

· Los dueños/habitantes de casas habitación deberán llamar o enviar un email para solicitar esta revisión por parte de un Ingeniero Estructurista
· En el caso de inmuebles de uso comercial deberán dar permiso los dueños o personal con la autoridad para permitir el acceso.
· Un ingeniero estructurista deberá asistir al inmueble y realizar estas validaciones y registro de evidencias.
· El ingeniero entregará estos datos vía electrónica que pueden incluir textos, grabaciones de video, fotografías, voz y cualquier evidencia que se pueda obtener.
· Los administradores del sitio Web deberán registrar esta información en la BD.
· Los ingenieros estructuristas podrían tener un formulario para subir toda esta información pero será más adelante.

Se puede iniciar con los datos registrado en el [Mapeo colaborativo 19s](https://www.google.com/maps/d/u/0/viewer?ll=19.368091947678618%2C-99.15332558349303&hl=en&z=12&mid=1_-V97lbdgLFHpx-CtqhLWlJAnYY)

Existe una iniciativa llamada [salvatucasa.mx](http://www.salvatucasa.mx/) con el fin de enlazar a arquitectos e ingenieros estructuristas con ciudadanos afectados pero el formulario está muy largo y es posible que las personas no lo llenen.

Sé que estoy omitiendo características y datos a tomar en cuenta de las partes involucradas pero debemos iniciar con un tipo MVP que incluya lo mínimo de privacidad e identificación de solicitantes e ingenieros estructuristas e iniciar iteraciones de mejora. Espero sus comentarios y sugerencias. Además [colaboraré](https://www.linkedin.com/in/ricardomeza/) en el Frontend Web.

Mis acciones:
1. Contactar a un Ingeniero Estructurista titulado y con la mayor experiencia para poder obtener más información y complementar este issue.
2. Iniciar el UX del sitio web y subir los documentos y el enlace al prototipo.

Por el momento tengo el siguiente wireframe como base (lo muestra en horizontal pero al dar clic lo muestra vertical):
![img_2727](https://user-images.githubusercontent.com/22286/30725015-40927334-9f07-11e7-9037-b46b0da8978a.JPG)

Este sitio Web será de largo plazo.

Espero sus cometarios y aportaciones.

**Comment by miguelsalazar** [comment]
@ricardomeza Me parecería súper valioso contactar al equipo de salvatucasa.mx y ver cómo podemos ayudarles, ya sea simplificando el website, ayudándoles a crear una herramienta para gestionar los reportes, etc.

**Comment by poguez** [comment]
@miguelsalazar @ricardomeza en dónde se organizan salvatucasa.mx?

**Comment by javierojeda94** [comment]
Sería súper interesante esto, la verdad

**Comment by ricardomeza** [comment]
@miguelsalazar @poguez ya los contacté, espero puedan registrar su proyecto aquí y lo podamos expandir.

**Comment by alanTorresManci** [comment]
Puedo ayudar desde la api hasta el desarrollo de la app (IOS)

**Comment by ricardomeza** [comment]
@alanTorresManci entra al slack codeandomexico.slack.com y al grupo #sismomx-obras para que veas el avance que ya tenían.

Yo estoy realizando unos wireframes que tal vez sirvan de base.

**Comment by Slackgirl92** [comment]
Buenas noches 
Ofresco mis servicios como desarrolladora para poder sacar a flote este proyecto , quedo a sus ordenes

**Comment by ricardomeza** [comment]
Los datos contemplados en esta aplicación se están almacenando en otras soluciones, para evitar duplicar esfuerzos debemos investigar si podemos apoyar ahi, mientras tanto cerraremos el issue para no distraerlos de los otros registrados.
¡Gracias por su interés!
