### ISSUE TITLE
Describir dinámica de AirBnb

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#14]
¿Qué es? ?cómo funciona? vigencia, etc.

**Comment by Deckon** [comment]
Hola, como ayudo con este issue?.

**Comment by jorgedeloera** [comment]
[https://www.airbnb.mx/welcome](url) se encuentra la descripción.

- Qué información y por qué canal se necesita para fomentar su uso

**Comment by gabelula** [comment]
Buscar información de como funciona Airbnb para casos de apoyo en estas situaciones y coloca la descripción en este mismo issue. De ahi alguien lo llevara a la página.

**Comment by lmauromb** [comment]
[Sitio de Airbnb](https://www.airbnb.mx/welcome/evacuees/terremotoenmexico)

**Comment by Deckon** [comment]
ok

**Comment by miguelsalazar** [comment]
¿Cuál es el output de éste issue?

**Comment by marcoC76** [comment]
Se creará un documento Google o directamente implementación en el sitio?

**Comment by miguelsalazar** [comment]
Agregar primero a [este documento](https://docs.google.com/document/d/1QVBq6UZ4JA24HceiTwUWfbcz3ZA3SxueOymXsnp43Ug/edit#) y el equipo de #sismomx-website decidirá qué hacer con él:

**Comment by xiam** [comment]
Como te sea más fácil @marcoC76, si enlazas un google doc lo podríamos "traducir" al sitio.

**Comment by Deckon** [comment]
Hola, Yo ta me encuentro trabajando sobre un markdown con la informacion. ¿No se si gusten que la suba al documento?

**Comment by marcoC76** [comment]
Si súbelo y ahí trabajamos

**Comment by Deckon** [comment]
Listo. Esta al final del documento

**Comment by Deckon** [comment]
¿Esta bien si se suben imágenes en el documento?

**Comment by Deckon** [comment]
Creo que eso es todo. ¿Falta algo mas?

**Comment by miguelsalazar** [comment]
No, todo perfecto @Deckon.
