### ISSUE TITLE
Ordenar la información

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/terremoto-cdmx#144]
Que no se vea toda la información posible a donar, que se vea sólo la información del rubro seleccionada. Es decir mostrar los elementos de la lista hasta después de un click

**Comment by ghost** [comment]
oigan hay problema si hago esto en js no desarrollo en ruby y estoy aprendiendo a hacer el pull request :/

**Comment by tlacoyodefrijol** [comment]
Está bien @evillasr. Antes revisaría cómo se vería con @almajaneiro, porque van a editar algunas cosas y van a hacer un mockup de esto.

**Comment by gabelula** [comment]
Ojo que todo estoy es en JS. No hay ruby en el codigo para el sitio. Se usan gemas para generacion de estaticos pero todo es JS, HTML y MD.

**Comment by ghost** [comment]
¿Cierro este entonces considerando que lo trabajarán los chicos del rediseño ?

**Comment by ghost** [comment]
Lo cierro ya que acomodé un poco mejor la info, aunque no se depliegue ahora el diseño del 160 lo considerará :D
