### ISSUE TITLE
jekyll server en windows crash 

### ISSUE THREAD

**Issue by GeraAlcantara** [CodeandoMexico/terremoto-cdmx#148]
Al correr el comando de jekyll server, en plataforma windows crashea y no inicia el server. 
Jekyll server testeado con un new site funciona correctamente en local host. 
 el mensaje de la terminal es el siguiente 

E:\Sites\terremoto-cdmx-master>jekyll server
Configuration file: E:/Sites/terremoto-cdmx-master/_config.yml
            Source: E:/Sites/terremoto-cdmx-master
       Destination: E:/Sites/terremoto-cdmx-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:29:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:29:in `block in process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:28:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-polyglot-1.3.1/lib/jekyll/polyglot/patches/jekyll/site.rb:28:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/command.rb:26:in `process_site'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/commands/build.rb:63:in `build'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/commands/build.rb:34:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/commands/serve.rb:40:in `block (3 levels) in init_with_program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/commands/serve.rb:40:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/commands/serve.rb:40:in `block (2 levels) in init_with_program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/exe/jekyll:13:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'

Talvez se pueda hacer algo, por lo tanto estoy tratando de buscar una solución al Fork()

**Comment by gabelula** [comment]
Miraste esto https://jekyllrb.com/docs/windows/ ?

**Comment by GeraAlcantara** [comment]
si lo vi pero el server si funciona 
pero no funciona con el site de terremoto-cdmx-master

![capture](https://user-images.githubusercontent.com/32178037/30729975-17b02bf6-9f29-11e7-9609-d187ef9eb366.PNG)
![capture2](https://user-images.githubusercontent.com/32178037/30729977-17b4de9e-9f29-11e7-965a-86d93258a96a.PNG)
![capture3](https://user-images.githubusercontent.com/32178037/30729976-17b1bb24-9f29-11e7-9f2f-436d7ef4e8ed.PNG)

**Comment by GeraAlcantara** [comment]
solucionado 
en el _config.yml hay que cambiar solo la línea de parallel_localization: true
y cambiarla a false

parallel_localization: false
