### ISSUE TITLE
Revisión de textos para hacerlos más legibles

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/terremoto-cdmx#149]
En algunos vínculos no se distingue clara la información , por ello corregiré los textos

**Comment by gabelula** [comment]
Comenta aca cuando tengas PR.

**Comment by ghost** [comment]
Listísimo :D acabo de hacer pr

**Comment by ghost** [comment]
Está hecho el PR y se resolvió con el diseño :D de hecho quito mi PR porque lo resolvieron con el diseño
