### ISSUE TITLE
Propuesta para hacer el sitio más interactivo (puede parecer demasiado texto)

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/terremoto-cdmx#150]
para que la página sea un poco más interactiva, ya que se amotina demasiado texto

**Comment by nr1q** [comment]
Tienes algo en mente o ya trabajando? Creo que todo puede quedar como una especie de índice, e ir accediendo al contenido por medio de clicks. Aunque creo que no todo estaría "oculto".

Tal vez habría que reestructurar un poco el html, para tener algo como la [documentación de openframeworks](http://openframeworks.cc/documentation/)

**Comment by dbautistav** [comment]
Los cambios que se vayan incorporando deberían considerar que sean útiles para todo tipo de usuarios, siguiendo principios de accesibilidad. Aquí algunos recursos:

- [A11y Command-line Tools](https://addyosmani.com/a11y)
- [The A11Y Project](http://a11yproject.com)
- [web accessibility](https://wa11y.org)

**Comment by thewarpaint** [comment]
En mi opinión solo se debería continuar el estilo de la introducción: dos preguntas muy sencillas que permiten filtrar el resto del contenido que se muestra. "Quiero ayudar" y "Necesito ayuda". Yo tenía la idea de hacer una navegación de ese estilo aquí: https://politeiamx.github.io/emergencia/

Para repetir la pregunta de @nr1q, ¿hay alguna propuesta concreta en mente?

**Comment by tlacoyodefrijol** [comment]
@almajaneiro está viendo algunos cambios de diseño. 

Si quieres @thewarpaint podemos seguir el tema en #160 .

**Comment by ghost** [comment]
Cierro este considerando que se continuará en el 160 con gente de diseño va?

**Comment by ghost** [comment]
Paso como solución con issue 160 :D
