### ISSUE TITLE
Resolver problemas de cache con jekyll

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#158]
En Safari sigo viendo problemas con el footer:

![screen shot 2017-09-22 at 06 56 09](https://user-images.githubusercontent.com/385670/30743463-548b2686-9f63-11e7-8399-a09119e3b9eb.png)

Mientras en Chrome está la versión más reciente:

![screen shot 2017-09-22 at 06 58 02](https://user-images.githubusercontent.com/385670/30743485-6e4afc40-9f63-11e7-97f6-fd70f7abbb16.png)

Hay forma no manual de que con cada build le digamos a Jekyll que invalide el archivo CSS?

```html
<link rel="stylesheet" href="assets/css/main.css">
```

Algo como:

```html
<link rel="stylesheet" href="assets/css/main.css?t=20170922060623">
```

¿O tal vez se pueda deshabilitar cache en CF? (cc @javierbyte)

**Comment by ageofzetta** [comment]
fixed with [169](https://github.com/CodeandoMexico/terremoto-cdmx/pull/169)

**Comment by ageofzetta** [comment]
@xiam ^

**Comment by xiam** [comment]
@ageofzetta gracias, podrías revisar esta duda https://github.com/CodeandoMexico/terremoto-cdmx/pull/169#discussion_r140519666?
