### ISSUE TITLE
Jerarquía de elementos H3

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#159]
El subtítulo "Teléfonos de emergencia" afecta a las dos columnas de teléfonos de emergencia:

![screen shot 2017-09-22 at 07 00 58](https://user-images.githubusercontent.com/385670/30743613-fbe995ca-9f63-11e7-9e32-86fffcd9eced.png)

Sin embargo la columna de la derecha queda a la misma altura que el subtítulo y parece restarle importancia, esto es porque el subtítulo actualmente va con la columna de la izquierda:

![screen shot 2017-09-22 at 07 02 58](https://user-images.githubusercontent.com/385670/30743645-1bd14c98-9f64-11e7-9fb1-552ed8f41203.png)

Esto resulta inconsistente con el resto de subtítulos en esa sección:

![screen shot 2017-09-22 at 07 03 56](https://user-images.githubusercontent.com/385670/30743706-6fa2f8b2-9f64-11e7-859e-69fa434b45da.png)

![screen shot 2017-09-22 at 07 05 54](https://user-images.githubusercontent.com/385670/30743720-8133d8e4-9f64-11e7-8de9-6e8826dba57c.png)

¿Podemos hacer algo para que los subtítulos tengan su propio espacio separado de su contenido?

**Comment by israads** [comment]
Se eliminó la sección de teléfonos de emergencia

**Comment by dbautistav** [comment]
Entonces se cierra el issue, o qué procede?

**Comment by tlacoyodefrijol** [comment]
Cerrermos. Me suena más a que era un tema de que faltaba un div en el título que un problema de estilos.  Gracias @dbautistav @israads @xiam
