### ISSUE TITLE
Crear directorio de centros de acopio

### ISSUE THREAD

**Issue by marcoC76** [CodeandoMexico/terremoto-cdmx#16]
Deberíamos crear una lista para saber que se necesita en las zonas afectadas, cómo agua, insulina y cosas por el estilo

**Comment by marcoC76** [comment]
atún, sardinas, frijoles, sopa, mayonesa, leche en polvo, galletas, café soluble, arroz, ropa nueva, ropa usada, zapatos, jabón, cepillos de dientes, papel higiénico, toallas sanitarias, zapatos, detergentes, cubetas, escobas, cloro y trapeadores.

**Comment by josuesfakee** [comment]
esto seria en un documento de google docs?
Me sumo para la ayuda.
SALUDOS!

**Comment by miguelsalazar** [comment]
Hay que revisar si no hay ya una lista de centros de acopio, deben haber varias. Si queremos curar la información que esté dispersa en la web sobre los centros de acopio, aquí dejo un documento:

https://docs.google.com/spreadsheets/d/1Twfore78tjnWzJTY2EHOlheh-8ue0KcRDI_VzAOoGEU/edit#gid=0

**Comment by miguelsalazar** [comment]
Cierro el issue porque ya está el documento creado. Tenemos que pasarlo al equipo de Información para que nos ayuden a llenar el documento.
