### ISSUE TITLE
La sección de teléfonos de emergencia está duplicada

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#161]
Tenemos teléfonos debajo de "Necesito Ayuda":

![screen shot 2017-09-22 at 07 14 55](https://user-images.githubusercontent.com/385670/30744023-cd44f528-9f65-11e7-8b9b-37ca8a07e5dc.png)

Y en "Teléfonos de emergencia en tu ciudad":

![screen shot 2017-09-22 at 07 14 35](https://user-images.githubusercontent.com/385670/30744004-b8f4be96-9f65-11e7-95cc-cfb767b33d10.png)

Podría ser mejor y más claro tener todo en un solo lugar.

**Comment by hrocha16** [comment]
Creo que lo mejor seria dejar la sección de necesito ayuda y quitar la de teléfonos de emergencia, que te parece?

**Comment by xiam** [comment]
Me parece bien, creo que hay algunos teléfonos en la sección de abajo que no están en la sección de arriba, ¿podrías unirlos?

Gracias!

**Comment by dbautistav** [comment]
Yo puedo trabajar en esto si nadie lo ha atendido.

@xiam, @hrocha16

**Comment by tlacoyodefrijol** [comment]
dale @dbautistav

**Comment by tlacoyodefrijol** [comment]
asignado a @dbautistav

**Comment by israads** [comment]
ups, ya está arriba

**Comment by xiam** [comment]
Cerrado por https://github.com/CodeandoMexico/terremoto-cdmx/pull/167

**Comment by hecerinc** [comment]
@xiam #167 no cierra este.

**Comment by hecerinc** [comment]
Also, si esto sigue en progreso estaría cool quedarnos con la de Teléfonos de emergencia (no necesariamente ahí pero ese contenido) porque tiene los links a teléfonos formateados en HTML y eso hace más sencillo que si lo abres en un móvil se puede ir directo al dial (Y)

**Comment by xiam** [comment]
Gracias @hecerinc, good catch! Reabriendo.

**Comment by tlacoyodefrijol** [comment]
entonces queda hasta que @dbautistav haga PR
