### ISSUE TITLE
Órden de sección de "Quiero Ayudar"

### ISSUE THREAD

**Issue by xiam** [CodeandoMexico/terremoto-cdmx#162]
La sección de "Quiero Ayudar" viene después de "Recursos":

![screen shot 2017-09-22 at 07 19 34](https://user-images.githubusercontent.com/385670/30744171-776afa16-9f66-11e7-81a8-58da937e13d7.png)

Sin embargo hay dos botones en el header que hacen suponer que las secciones "Necesito Ayuda" y "Quiero Ayudar" son principales:

![screen shot 2017-09-22 at 07 20 59](https://user-images.githubusercontent.com/385670/30744201-9a55b4da-9f66-11e7-9e4e-5c8e1d4f2af7.png)

¿Podríamos mover la sección para que quede debajo de "Necesito Ayuda"?

**Comment by hecerinc** [comment]
https://github.com/CodeandoMexico/terremoto-cdmx/pull/167
