### ISSUE TITLE
Links a 'Necesito Ayuda' no estan actualizados

### ISSUE THREAD

**Issue by gilfranfer** [CodeandoMexico/terremoto-cdmx#164]
cambiar link de #section-rescatados a #section-necesito ayuda
Dos lugares identificados:  Heades y Post de Botones

**Comment by gilfranfer** [comment]
PR #163  for this issue

**Comment by gilfranfer** [comment]
Link en footer tambien es incorrecto...
Fixing now ...

**Comment by xiam** [comment]
Resuelto https://github.com/CodeandoMexico/terremoto-cdmx/pull/163
