### ISSUE TITLE
Mejorar Botones (general)

### ISSUE THREAD

**Issue by fmicalizzi** [CodeandoMexico/terremoto-cdmx#165]
Los botontes a continuación se pierden en el diseño. 
Habría que mejorar el CSS de los mismos.

- MOSTRAR LISTA DE RESCATADOS
- CARGAR MAPA
- MOSTRAR LISTA
- MOSTRAR MAPEO
- Google Person Finder
- MOSTRAR MAPA
- MOSTRAR MAPA

Tienen una referencia de como deberían ser aquí: http://159.203.97.29/

![captura de pantalla 2017-09-22 a la s 08 50 47](https://user-images.githubusercontent.com/626004/30747508-29d2d3fc-9f73-11e7-9e00-a4ee2947d194.png)

**Comment by felipejacob** [comment]
Asignamelo

**Comment by tlacoyodefrijol** [comment]
Asignado a @felipejacob

**Comment by ageofzetta** [comment]
@tlacoyodefrijol  ya lo estoy viendo yo

**Comment by ageofzetta** [comment]
@tlacoyodefrijol  fixed with PR [170](https://github.com/CodeandoMexico/terremoto-cdmx/pull/170)

**Comment by felipejacob** [comment]
Ok, si necesitas algo aqui ando
