### ISSUE TITLE
Sección de promesas por parte de gobierno/empresas públicas y privadas

### ISSUE THREAD

**Issue by alexfuser** [CodeandoMexico/terremoto-cdmx#166]
Tengo una idea que pudiera ponerse en la sección de https://sismomexico.org/ donde recopile las promesas de todo el gobierno federal como de los municipales que se han hecho, como de empresas, organizaciones, etc con los afectados del sismo en todas las entidades y trabajos futuros, para que no queden en el olvido y a palabras que se las puedan llevar el viento. No me gustaría que volviéramos a tener puras promesas incumplidas más que el año que viene hay cambio de gobierno. Se necesitaría que todos podamos mapear esas promesas e ir poniendo en un drive para recopilarlas y ponerlas en la página con todo screenshot o recurso donde las mencionen para tener pruebas también y de quien la dijo y su cargo.

**Comment by JPIglesias-Triangle** [comment]
Me parece muy buena idea!

**Comment by JPIglesias-Triangle** [comment]
Hay que recopilarlas como dices... En un drive o algo así. Ya tienes uno? O lo hago?

**Comment by gilfranfer** [comment]
@alexfuser se van a desplegar en la pagina con html y Js?, o solo piensan poner el GSheet?

**Comment by israads** [comment]
La página ya está muy larga, creo que es mejor en otra sección, así ayuda igual al SEO

**Comment by K-TO** [comment]
Hola, en que les puedo ayudar?

**Comment by alexfuser** [comment]
@JPIglesias-Triangle ya tengo uno https://docs.google.com/spreadsheets/d/1qxkntj4OvjRbT3NcQpJkOPvKbZhQlWKo0RZu95guKPw/edit#gid=0

**Comment by alexfuser** [comment]
Estoy trabajando por afuera, para no saturar y moverme rápido. Este es el repositorio donde @jorandradefig lo ha creado y que estamos apoyando tambien estas iniciativas https://github.com/jorandradefig/Promesas

**Comment by alexfuser** [comment]
@K-TO necesitaríamos ayuda para recolección de datos y tal vez en la visualización de los mismos.

**Comment by alexfuser** [comment]
@gilfranfer Vamos a hacer una web landing y visualizar los datos desde el spreadsheet para no andar haciendo dobles esfuerzos.

**Comment by alanTorresManci** [comment]
@alexfuser Puedo ayudar en el front de la landing, o en el back 🤷‍♀️

**Comment by hugovom** [comment]
qué necesitan?

**Comment by alexfuser** [comment]
@alanTorresManci si, lo haremos con angular puedes pasar aqui por fa https://github.com/jorandradefig/promesas.mx/issues

**Comment by alexfuser** [comment]
@hugovom primero ayudar a levantar el sitio, ya andamos en ello y segundo, mucha ayuda a mapeo y de juntar la información por estado dañado.

**Comment by gabelula** [comment]
Excelente! Vamos a cerrar este issue y agregar proyecto al README.
