### ISSUE TITLE
Agregar documento de Mapeo Colaborativo de la EDN

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/terremoto-cdmx#17]
Reemplazar la Lista de Reportes Ciudadanos por el documento de Mapeo Colaborativo (https://docs.google.com/spreadsheets/u/1/d/1ijleBcHJH_3V2nbMeXTjH4hTDYsjcdodYvHqhTc8C8c/edit#gid=0). El documento de Mapeo Colaborativo es la fuente oficial lanzada por la Estrategia Digital Nacional.

**Comment by basicavisual** [comment]
yo lo agarro

**Comment by joseetmanuel** [comment]
Igual yo estoy en eso...

**Comment by miguelsalazar** [comment]
Quien lo tenga, asígneselo.

**Comment by basicavisual** [comment]
este ya debe quedar cerrado @almarngl
