### ISSUE TITLE
Fix new button style for mobile

### ISSUE THREAD

**Issue by gilfranfer** [CodeandoMexico/terremoto-cdmx#174]
Cuando el texto es muy largo, los botones nuevos se ven cortados en móvil.

**Comment by K-TO** [comment]
Asignamelo a mi.

![screenshot_20170922-124657](https://user-images.githubusercontent.com/10998021/30758249-2b61bcdc-9f97-11e7-9269-94f9929898f7.png)

**Comment by K-TO** [comment]
He realizado el ajuste, asi se ve actualmente.

![image](https://user-images.githubusercontent.com/10998021/30769813-2c9a10a0-9fe6-11e7-9db2-a7794160faa5.png)

**Comment by gilfranfer** [comment]
Thanks @K-TO !
