### ISSUE TITLE
Diseño: Botónes NECESITO AYUDA

### ISSUE THREAD

**Issue by JPIglesias-Triangle** [CodeandoMexico/terremoto-cdmx#179]
Lo que discutimos en el canal sismomx-gráfico, agregarle a esos botónes:
<img width="357" alt="captura de pantalla 2017-09-22 a la s 15 42 16" src="https://user-images.githubusercontent.com/24706093/30763832-c5f5200c-9fad-11e7-8b6f-b8c2e9a1bac3.png"> una propiedad de transition.

**Comment by JPIglesias-Triangle** [comment]
Y checarlos en mobile

**Comment by alanTorresManci** [comment]
puedo ayudar en el front, asigname el issue y lo platicamos en slack

**Comment by gabelula** [comment]
@alanTorresManci ASIGNADO a vos.
