### ISSUE TITLE
Agregar proyectos

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/terremoto-cdmx#180]
Agregar los siguientes proyectos a la tabla de [proyectos abiertos](https://github.com/CodeandoMexico/terremoto-cdmx#proyectos-abiertos)

Nuevos proyectos

- Banco de tiempo
  - Slack: #sismomx-banco-tiempo
  - GH: https://github.com/Janee/sismomx-banco-tiempo
- Acopio-UI
  - Slack: #sismomx-acopio-ui
  - GH: https://github.com/Skycatch/acopio-ui
- Revisa Mi Grieta (API)
  - Host: http://digaresc.info/revisamigrieta-api-backend/
  - Slack: #sismomx-obras
  - GH: https://github.com/digaresc/revisamigrieta-api-backend
- Revisa Mi Grieta (Bot)
  - Host: http://www.twitter.com/RevisaMiGrieta
  - Slack: #sismomx-obras 
  - GH: https://github.com/codersmexico/revisa-mi-grieta-bot
- Verificado19s
  - GH: https://github.com/parismend/Temblor
  - Slack: #sismomx-verificado19s
- SMS Brigadistas
  - GH: https://github.com/rbdr/sms-brigadistas
  - Slack: #sismo-sms-brigadistas
- Contribuye (Harvest)
  - Slack: #sismomx-contribuye
  - GH: https://github.com/CodeandoMexico/contribuye-harvest
- Contribuye (Front)
  - Slack: #sismomx-contribuye
  - GH: https://github.com/CodeandoMexico/contribuye-front
- Fuerza México
  - Host: https://play.google.com/store/apps/details?id=com.coders.fuerzamexico&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
  - GH: https://github.com/kimetrics/add-fuerzamexico-android
  - Slack: #sismomx-fuerza-mexico
- Localizador de personas hopsitalizadas
  - Host: http://localizador.sismomexico.org
  - GH: N/A
  - Slack: N/A

**Comment by gabelula** [comment]
Agregar este: https://github.com/jorandradefig/promesas.mx

**Comment by HzJavier** [comment]
@miguelsalazar a que te refieres con esto? ```Cambiar fake news bot y twiiter_bot```

**Comment by HzJavier** [comment]
Hecho en [#185](https://github.com/CodeandoMexico/terremoto-cdmx/pull/185)

**Comment by luispeerez** [comment]
Por favor si podrian cerrar este issue y hacer merge del pull request

**Comment by miguelsalazar** [comment]
Merged. This closes #185.
