### ISSUE TITLE
Diseño: Imagen de la Header

### ISSUE THREAD

**Issue by JPIglesias-Triangle** [CodeandoMexico/terremoto-cdmx#181]
Aquí está la imagen que debería ir en la header (cómo fondo). Cómo yo ya me hice bolas con Jekyll y eso la pongo aquí para que un alma caritativa la ponga 🤣 

Imagen (comprimida): 
![sismomx header-min](https://user-images.githubusercontent.com/24706093/30765072-48c6d67e-9fb3-11e7-8f36-7604dae1c44c.png)

**Comment by coderdiaz** [comment]
Yo la agrego 👍

**Comment by JPIglesias-Triangle** [comment]
Gracias @coderdiaz
