### ISSUE TITLE
Imágenes satelitales de alta resolución a frecuencias intra-semanal

### ISSUE THREAD

**Issue by noise-trader** [CodeandoMexico/terremoto-cdmx#182]
Hola a todos.  Me encantaría contribuir a este proyecto.  Acabo de contactar a la empresa Planet, quienes recolectan fotografía satelital a altas resoluciones y de manera intra-semanal.  Me compartieron esta liga: https://www.planet.com/disaster/earthquake-in-mexico-2017-09-20/.  Estamos viendo cómo hacer para que nos liberen su información a altas frecuencias para poder monitorear los esfuerzos de asistencia y monitoreo de recuperación.  ¿Cómo puedo contribuir?

**Comment by ageofzetta** [comment]
@noise-trader pon ésto en slack:
https://codeandomexico.slack.com/

**Comment by ageofzetta** [comment]
@tlacoyodefrijol  ésto no es issue
