### ISSUE TITLE
Diseño: Botón QUIERO AYUDAR

### ISSUE THREAD

**Issue by JPIglesias-Triangle** [CodeandoMexico/terremoto-cdmx#183]
![screen shot 2017-09-22 at 16 50 40](https://user-images.githubusercontent.com/24706093/30765786-ff2c35be-9fb6-11e7-84ba-f7df70285b12.png)

Cambiar el link de hasta abajo por un Call To Action para que quede claro que se puede colaborar...

**Comment by AJPalacios** [comment]
Como puedo aportar a el diseño del boton !

**Comment by baezor** [comment]
@JPIglesias-Triangle  Yo puedo trabajar en esto!

**Comment by AJPalacios** [comment]
Que opinan de esto ! 

@JPIglesias-Triangle 


![snip_20170922180630](https://user-images.githubusercontent.com/11066097/30767268-d66461ba-9fc0-11e7-8916-bfa7275463f1.png)

**Comment by baezor** [comment]
@AJPalacios Me gusta, ya mandaste PR con tu cambio?

**Comment by huhgawz** [comment]
Asi es como se ve ahora:

![screenshot-2017-09-23_01-57-09](https://user-images.githubusercontent.com/369338/30770945-a792c894-a002-11e7-9f6b-166b816a527a.png)
