### ISSUE TITLE
Agregar info de bancos de sangre

### ISSUE THREAD

**Issue by vfoss** [CodeandoMexico/terremoto-cdmx#19]
-Ubicaciones de bancos de sangre en los áreas afectados y en otros estados que están recopilando para los damnificados

**Comment by lmauromb** [comment]
Checa [Blooders](https://blooders.org/) :)

**Comment by miguelsalazar** [comment]
Sería bueno agregar ésto al [documento de referencia](https://docs.google.com/document/d/1QVBq6UZ4JA24HceiTwUWfbcz3ZA3SxueOymXsnp43Ug/edit#) y al README.

**Comment by AlexMaguey** [comment]
¿Ya hay alguien trabajando en este issue? Me gustaría trabajar en este.

**Comment by vfoss** [comment]
No, hazlo @AlexMaguey.  Sólo sé de esto en Guadalajara: http://www.notisistema.com/noticias/buena-respuesta-al-llamado-de-donar-sangre-para-heridos-por-el-sismo/

**Comment by gabelula** [comment]
@AlexMaguey Esto ya lo hiciste, no? Podremos cerrar issue?
