### ISSUE TITLE
Agregar "Guía para reclamar seguros por terremoto"

### ISSUE THREAD

**Issue by jashk** [CodeandoMexico/terremoto-cdmx#196]
Desde http://www.pequenocerdocapitalista.com/guia-reclamar-seguros-terremoto/ han publicado una guía para reclamar seguros por terremoto.

Creo que es información muy útil que podría ir en **Necesito Ayuda** -> **Asesoría Jurídica** 

Propongo agregar el enlace y un botón para descargar la guía.

Enlace de descarga del documento: https://www.dropbox.com/s/pedizh9i2jivh3c/Guía%20para%20reclamar%20seguros%20por%20terremoto%20%202017.09.22.pdf?dl=1

**Comment by stefanya131** [comment]
Me interesa 😊

**Comment by jashk** [comment]
@stefanya131 adelante !

**Comment by tlacoyodefrijol** [comment]
@stefanya131 te lo asignamos a ti?

**Comment by lasr21** [comment]
si @stefanya131 no puede me gustaría ayudar con este issue :)

**Comment by tlacoyodefrijol** [comment]
dale @lasr21 te lo asigno a ti. En Slack entró @Javgutar, que es abogado y quizá pueda ayudar en algo en el issue.

**Comment by jashk** [comment]
Yo mandé un tweet a PeqCerdoCap para que sepan que vamos a incluir la guía

**Comment by tlacoyodefrijol** [comment]
@lasr21 probablemente tengamos que pausar este un poco, porque esto iría más bien en una sección de "Qué hacer una vez que pasaron varios días" o algo así.

**Comment by lasr21** [comment]
@tlacoyodefrijol oki, espero. aunque de acuerdo a la guía 

6. ¿Qué plazos existen para iniciar una reclamación?
Las acciones derivadas de la póliza (los derechos) prescriben a los dos años en pólizas de bienes de acuerdo con los artículos 66, 67, 68 y 81 de la Ley Sobre el Contrato de Seguro, PERO en las condiciones de las pólizas te piden que des aviso en un **plazo máximo de 5 días hábiles a partir del siniestro**. En caso de retraso se podría reducir la cantidad de la indemnización.
Tras la reclamación, la aseguradora te debería de resolver en 30 días naturales.

**Comment by jashk** [comment]
Propongo continuar con la idea original de **Necesito Ayuda** -> **Asesoría Jurídica**

![Alt text](https://monosnap.com/file/QlSxUZHmDPdmAyRbT6SasNUu358S9U.png)

**Comment by lasr21** [comment]
https://github.com/CodeandoMexico/terremoto-cdmx/pull/206
