### ISSUE TITLE
quitar https de comoayudar.mx

### ISSUE THREAD

**Issue by clasig** [CodeandoMexico/terremoto-cdmx#197]
Siendo cualquier usuario, quiero entrar al sitio comoayudar.mx #

**Descripción del problema:**
el código fuente de la página tiene la url con https, pero el sitio comoayudar.mx no tiene ssl 

**Pasos para reproducir:**
click en el link de:
DONA DEPOSITANDO
Entra a comoayudar.mx y podrás consultar un amplio listado de sitios y cuentas dónde donar.

**Resultado obtenido:**
manda a la alerta de página peligrosa, o simplemente no carga el sitio 

**Resultado esperado:**
entrar al sitio comoayudar.mx

**Entorno:**
n/a

**Comment by hrocha16** [comment]
https://github.com/CodeandoMexico/terremoto-cdmx/pull/202 Good catch! 🎉

**Comment by miguelsalazar** [comment]
Ve al repositorio de su proyecto (está en el README).

**Comment by hrocha16** [comment]
@miguelsalazar Se refiere al link que está en la sección de DONA DEPOSITANDO que lleva a comoayudar.mx, estaba con https y el sitio no tiene por eso chrome lo marca como inseguro, lo deje como http y el link ya funciona bien.
