### ISSUE TITLE
texto repetido en sección "Contribuye con código"

### ISSUE THREAD

**Issue by clasig** [CodeandoMexico/terremoto-cdmx#198]
Siendo n/A, quiero hacer n/A para poder n/A

**Descripción del problema:**
Este texto se repite en la sección:

> Si eres ingeniero civil, arquitecto, médico o carrera a fin, se solicitan voluntarios para asistir a Protección Civil en la revisión de edificios. Ponerse en contacto con Alfonso Rivero al celular 55 4448 7863.

**Pasos para reproducir:**
n/A

**Resultado obtenido:**
n/A

**Resultado esperado:**
n/A

**Entorno:**
n/A

**Comment by lasr21** [comment]
PR para elimiar el texto https://github.com/CodeandoMexico/terremoto-cdmx/pull/201

**Comment by lasr21** [comment]
@tlacoyodefrijol puedes cerrar este issue?
