### ISSUE TITLE
Mapeo de tweets con categorias de ayuda y localización 

### ISSUE THREAD

**Issue by paulinabustos** [CodeandoMexico/terremoto-cdmx#20]
Estamos consumiendo todos los tweets que tienen palabras claves de solicitar ayuda, clasificando por categorías (Comida, Agua, Herramientas, etc) y mapeando los voluntarios con las persona que piden la ayuda. 

Mockup: https://app.moqups.com/civica-digital/d4yHUXskVr/view

Escenarios principales: 
1.- Como voluntario encuentro las categorías que necesitan más ayuda. 
2.- Como voluntario me apunto para dar ayuda en esa categoría 
3.- Como persona que pide ayuda, recibo un SMS de aviso que alguien se apunto en dar ayuda

**Comment by miguelsalazar** [comment]
Compartí esto en el canal de #sismomx-realtime, dentro del Slack de Codeando México. Hay un esfuerzo similar y creo que podrían sumar.

**Comment by santosr09** [comment]
Hola, puedo ayudar en algo con este issue??

**Comment by pel-daniel** [comment]
@santosr09  En slack (http://slack.codeandomexico.org/) estan coordinando todo. En los canales que empiezan con sismomx

**Comment by DarioCM** [comment]
Hola, estamos generando algo parecido con un cliente de tweeter y un filtrado mediante patrones con expresiones regulares. Estamos generando los sioguientes datos (ejemplo) ya filtrados, quitando tweets basura 

Result{fecha=' 20/09 22:01', seNecesita='  Alimento pañales', tipoPersona='bebe', donde='División del Norte y Churubusco'}
Result{fecha='null', seNecesita='  clavos lonas víveres', tipoPersona='null', donde='Pacífico 223'}

**Comment by miguelsalazar** [comment]
Seguir conversación en `#sismomx-realtime`
