### ISSUE TITLE
Abrir enlaces externos en un target _blank

### ISSUE THREAD

**Issue by bjardon** [CodeandoMexico/terremoto-cdmx#205]
Propongo que los enlaces que lleven a páginas externas se abran en un target `_blank`, es decir, en una ventana o pestaña nueva.

Esto ayuda a la navegabilidad del sitio, porque permite que los usuarios vean referencias externas; pero mantengan su navegación en el sitio.

**Comment by LittaPanda** [comment]
Lo tomo. Saludos :)

**Comment by gabelula** [comment]
Asignado a ti LittaPanda!

**Comment by LittaPanda** [comment]
Resuelto en PR #222 fix-205

**Comment by ghost** [comment]
Debería cerrarse, ya se cumple
