### ISSUE TITLE
Ajustar Styling botones "Agregar Centro de Acopio" y Otros

### ISSUE THREAD

**Issue by fmicalizzi** [CodeandoMexico/terremoto-cdmx#207]
Siendo analista UX, quiero pedir que se haga un ajuste en CSS para lograr que los Botones del sitio estén unificados y ágiles para los usuarios del sitio.

Descripción del problema: Los botones 
-agregar centro de acopio"
-Reportar daños y derrumbes  
-Reportar centros de acopio  
-Reportar daños y derrumbes
No respetan el diseño general de los botones del sitio.
![captura de pantalla 2017-09-22 a la s 21 29 28](https://user-images.githubusercontent.com/626004/30769408-2f0b49de-9fdd-11e7-9bde-7b5050695648.png)

Pasos para reproducir: deberían ajustar la hoja de estilos o el código del front-end para que respeten el diseño de todos los botones

Resultado esperado: botones normalizados según hoja de estilos

Ejemplo a seguir:
![captura de pantalla 2017-09-22 a la s 21 23 42](https://user-images.githubusercontent.com/626004/30769393-d3d6d862-9fdc-11e7-9851-f39f38b557ad.png)

**Comment by baezor** [comment]
@JPIglesias-Triangle creo que puede resolverlo, él estaba trabajando en el update.

**Comment by astrocumbia** [comment]
Solucionado en este PR https://github.com/CodeandoMexico/terremoto-cdmx/pull/214

**Comment by baezor** [comment]
Resuelto! 👍 
![screenshot 2017-09-23 00 56 29](https://user-images.githubusercontent.com/3989321/30770620-e1932a82-9ffa-11e7-8f2c-97a3d2ac9c24.png)
