### ISSUE TITLE
Agregar encuesta para añadirse como voluntario en la sección de "Quiero Ayudar"

### ISSUE THREAD

**Issue by baezor** [CodeandoMexico/terremoto-cdmx#209]
[Jorge](https://twitter.com/ComensalEnDF/status/911389280416751616) Hizo una encuesta de Survey monkey donde lleva más de 60 voluntarios registrados, creo que sería buena idea agregarlo dentro de la sección de "Quiero ayudar". Si están de acuerdo, yo puedo agregarlo.

**Comment by astrocumbia** [comment]
Voy a trabajar en esto :)

**Comment by manonfire** [comment]
Ya van 100, aquí el tema es cómo les hago llegar las respuestas

**Comment by baezor** [comment]
Resuelto 👍 
![screenshot 2017-09-23 01 01 25](https://user-images.githubusercontent.com/3989321/30770614-bc8d56ea-9ffa-11e7-804a-a4908757ebff.png)
