### ISSUE TITLE
Crear un bot en twiiter con las principales provedoras de servicios CFE,CONAGUA,ETC se acepta ayuda

### ISSUE THREAD

**Issue by nusspez** [CodeandoMexico/terremoto-cdmx#211]
paso 1
crear una lista de los usuarios de twiter a los que se les hara retewt (principalmente servicios)
agua,luz,gas,drenaje, etc 
paso 2 
crear el correo el boot y empezar a programar 
paso 3 
crear el repositorio en github

**Comment by m4grio** [comment]
Yo puedo ayudar con esto.
Me pasan las cuentas y algunos criterios para hacer RT con el bot?

**Comment by baezor** [comment]
Algún avance de esta idea, ya se está trabajando en ello?

**Comment by m4grio** [comment]
Está por acá: https://github.com/nusspez/bot-servicios-471
Podemos cerrar este issue.

**Comment by fmicalizzi** [comment]
Estimados los invito a revisar estos PR
1- https://github.com/carlosherrera/cdmxbot
2- https://github.com/Garyi/Filtro-Informaci-n-Valiosa-Terremoto-Twitter
3- https://github.com/regenhans/earthquake-bot

Además en slack #sismomx-bots hay gente abocada a los Bots
