### ISSUE TITLE
CTA duplicado: Reportar daños y derrumbes

### ISSUE THREAD

**Issue by arianapazr** [CodeandoMexico/terremoto-cdmx#212]
**Descripción del problema:**
Existen dos CTA que dirigen al mismo link
**Pasos para reproducir:**

1. Ir a http://sismomexico.org/#section-quiero_ayudar
2. Sección Agrega centros de apoyo

**Resultado obtenido:**
2 CTA con texto repetido, dirigen a mismo link
**Resultado esperado:**
1 CTA que diriga al Gdocs correspondiente
**Entorno:**
http://sismomexico.org/
<img width="956" alt="cta" src="https://user-images.githubusercontent.com/26688844/30770117-d229645c-a05a-11e7-9a74-566163613e5b.png">

**Comment by astrocumbia** [comment]
Voy a trabajar en ello

**Comment by baezor** [comment]
Resuelto 👍 
![screenshot 2017-09-23 00 56 29](https://user-images.githubusercontent.com/3989321/30770577-0e08f89a-9ffa-11e7-9b60-1543de4358b4.png)
