### ISSUE TITLE
Agregar https://donativos.conekta.com/ a la parte de donativos

### ISSUE THREAD

**Issue by lasr21** [CodeandoMexico/terremoto-cdmx#213]
Agregar a https://donativos.conekta.com/ en las opciones de donativo

**Comment by astrocumbia** [comment]
Voy a trabajar en esto

**Comment by baezor** [comment]
Resuelto! 👍 
![screenshot 2017-09-23 00 46 18](https://user-images.githubusercontent.com/3989321/30770521-b33fceda-9ff8-11e7-8bd7-2484d59ea868.png)
