### ISSUE TITLE
Ajustar Links para que sean _blank

### ISSUE THREAD

**Issue by fmicalizzi** [CodeandoMexico/terremoto-cdmx#22]
Evitar sacar al user desde la página de inicio para que puedan volver a buscar la información

**Comment by MisaelSalcido** [comment]
Yo me ofrezco

**Comment by negMarko** [comment]
yo también me ofrezco

**Comment by MisaelSalcido** [comment]
Ya está resuelto este issue, estaría bien cerrarlo?

**Comment by xiam** [comment]
@MisaelSalcido gracias, creo que te faltó el pull request, avísanos si necesitas una mano para eso

**Comment by xiam** [comment]
@MisaelSalcido nvm, no lo veo pero ya está en el lugar que le corresponde. Gracias!

**Comment by MisaelSalcido** [comment]
Hola @xiam, vi que pusieron links en el FAQ pero estos no se abren en nuevas pestañas, quieres que también me encargue de esos?

**Comment by ponentesincausa** [comment]
@miguelsalazar @almarngl  ^^
