### ISSUE TITLE
Tag <div> que se renderea como texto

### ISSUE THREAD

**Issue by KernelPanicCode** [CodeandoMexico/terremoto-cdmx#221]
En la sección **Contribuye con código** , después de la sentencia "Dona tus habilidades...."

hay un tag `</div>` que se renderea como texto. Es decir, no se interpreta como html y se despliega como otro parrafo.  Supongo que era para dar un espacio entre el texto "Dona tus habiidades..." y la lista posterior. 

Ya estoy en ello.

**Comment by LittaPanda** [comment]
lo arregle en el pull request fix-205 :)

**Comment by KernelPanicCode** [comment]
Perfecto

**Comment by juliobarreraa** [comment]
Entonces, este ticket ya estaría cerrado, ¿no?

**Comment by LittaPanda** [comment]
@juliobarreraa  Supongo que hasta que se haga merge del PR #222 :)
Saludos

**Comment by LittaPanda** [comment]
Pueden marcar esto como cerrado.
Está incluido en el PR #222 el cual ya fue unido al master
Saludos
