### ISSUE TITLE
Formulario para volunatarios cerrado

### ISSUE THREAD

**Issue by juanpflores** [CodeandoMexico/terremoto-cdmx#232]
**Descripción del problema:** Formulario de registro de voluntarios para el fin de semana del 23-24 de Septiembre no permite hacer el registro. 

**Pasos para reproducir:**

1.  Hacer click en el registro de voluntarios
<img width="980" alt="captura de pantalla 2017-09-23 a la s 13 12 38" src="https://user-images.githubusercontent.com/6200135/30775832-4714f726-a061-11e7-85a8-b4289a72d9d7.png">

**Resultado obtenido:** La pantalla de survey monkey estableciendo que el formulario esta cerrado. 

<img width="1264" alt="captura de pantalla 2017-09-23 a la s 13 13 16" src="https://user-images.githubusercontent.com/6200135/30775828-30fd5e10-a061-11e7-941b-3d98d6ab5574.png">

**Resultado esperado:**  Un formulario para registrarse como voluntario. 

**Entorno:** NA

**Comment by hrocha16** [comment]
Creo que lo mejor seria quitar el link hasta tener uno que funcione, qué opinas?

**Comment by juanpflores** [comment]
@hrocha16 Creo que lo mejor sería quitar ambos el subtitulo y el link para evitar problemas. ¿Quiéres tomar ese issue?

**Comment by hrocha16** [comment]
Si, yo lo hago
