### ISSUE TITLE
Eliminar corazón rosa y la barra negra

### ISSUE THREAD

**Issue by yosoyrbk** [CodeandoMexico/terremoto-cdmx#239]
Siendo disenador, quiero hacer Eliminar corazón rosa y la barra negra para poder mejorar la interfaz para moviles, tambien agregar botones de quiero y necesito

**Descripción del problema:**

**Pasos para reproducir:**

**Resultado obtenido:**

**Resultado esperado:**
Que la interfaz movil sea mas efectiva 

**Entorno:**

**Comment by baezor** [comment]
Yo me puedo encargar de esto

**Comment by baezor** [comment]
¿Debe quedar así @yosoyrbk ?
![screenshot 2017-09-23 22 21 19](https://user-images.githubusercontent.com/3989321/30779140-8b134f08-a0ad-11e7-9986-41a1d8a8c9bd.png)

**Comment by yosoyrbk** [comment]
Muchas gracias Baezor!!

**Comment by baezor** [comment]
pero, ¿si está bien? para mandar el PR.

**Comment by yosoyrbk** [comment]
Se podría centrar el texto en la franja rosa?

**Comment by baezor** [comment]
está centrado, ¿no?, o ¿a qué te refieres?

**Comment by NotZombieFood** [comment]
yo creo que  si la idea es que se vean los botones, tendrían que hacerse un poco más pequeño el logo para que si se pudieran ver en la pantalla

**Comment by jrmm22** [comment]
Se refiere a centrado verticalmente en la pantalla

**Comment by NotZombieFood** [comment]
el texto está centrado pero no se ve completo el div

**Comment by yosoyrbk** [comment]
Listo!

**Comment by baezor** [comment]
Creo que acabo de tener una bonita idea, estamos desperdiciando espacio con el logo, y podríamos reestructurar para que los principales CTA queden a primer vista. Ahorita les mando screenshot

**Comment by gilfranfer** [comment]
La idea era dejar en el Header, las ligas a Quiero Ayudar y Necesito Ayuda... Dónde estaba el corazón rosado. No sé cómo se vería y si entre

**Comment by baezor** [comment]
Esta es mi propuesta, para que los botones que importan, estén a primera vista, sino, manden propuestas y lo hacemos
![screenshot 2017-09-23 22 58 08](https://user-images.githubusercontent.com/3989321/30779308-b02abcfe-a0b2-11e7-9d22-9b56fe9ce7e5.png)

**Comment by gilfranfer** [comment]
Se ve bien. La pregutna ahora es... El cambio en el tamaño de la primer sección será solo para la versión Movil, mientras la Web normal conserva su tamaño original?.
Has probado moviento los botones al top de la seccion rosada, antes de los textos que robas espacio?

**Comment by jrmm22** [comment]
A mi me gusta esa version que mandaste. Insisto, yo no soy disenador ni se de eso, simplemente me interesa que los botones salgan al inicio (para que si alguien necesita ayuda no tenga que buscar en la pagina).
Creo que ya que estas moviendo eso en el diseno podrias resolver el issue 250 (Cambiar necesito ayuda antes de quiero ayudar)

**Comment by gilfranfer** [comment]
Si, a mi tambien me gusta esa version, solo quiero saber si se va a afectar el tamaño de la primera sección en web tambien, o solo seria en Mobile. Y tambien poniendo los botones antes del texto puede darle otro toque que valdria la pena revisar.

**Comment by baezor** [comment]
@jrmm22 también me interesa que los CTA que nos importan sean de mayor prioridad. 
@gilfranfer 
1. Sí, esto se vería nadamas en mobile. 
2. ¿te refieres a mover los botones antes que el texto?, deja le muevo y vemos.

**Comment by baezor** [comment]
con los botones arriba de texto: 
![screenshot 2017-09-23 23 15 16](https://user-images.githubusercontent.com/3989321/30779392-1cf63c4e-a0b5-11e7-8a4d-511ba5907ff8.png)

**Comment by gilfranfer** [comment]
Me agrada esa version. 
Como dice @jrmm22  ahi mismo puedes poner el de Necesito Ayuda primero, para cerrar el otro issue de una vez. Ese cambio de orden tambien iria en el footer.

**Comment by NotZombieFood** [comment]
me agrada esta última :)

**Comment by jhovanarivas** [comment]
![30779392-1cf63c4e-a0b5-11e7-8a4d-511ba5907ff8](https://user-images.githubusercontent.com/32155870/30779544-24a11bae-a0b9-11e7-93fb-adc72ea65dc1.png)

**Comment by jhovanarivas** [comment]
![30779392-1cf63c4e-a0b5-11e7-8a4d-511ba5907ff8](https://user-images.githubusercontent.com/32155870/30779547-325312e8-a0b9-11e7-9e7f-6262b8f00eb8.jpg)

**Comment by gilfranfer** [comment]
Si estaría bien quitar el salto de línea, pero solo para mobile.

**Comment by baezor** [comment]
Listo los cambios!, gracias a todos!. 
![screenshot 2017-09-24 00 13 00](https://user-images.githubusercontent.com/3989321/30779700-272d4d76-a0bd-11e7-82e5-618230e1e2e1.png)
