### ISSUE TITLE
Actualizar README 12:00

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/terremoto-cdmx#24]
Actualizar el README con la información más importante al momento, basándose en el [documento de referencia](https://docs.google.com/document/d/1QVBq6UZ4JA24HceiTwUWfbcz3ZA3SxueOymXsnp43Ug/edit#) y actualizando la sección de [Cómo ayudar](https://github.com/CodeandoMexico/terremoto-cdmx#cómo-ayudar)

**Comment by gabelula** [comment]
Aqui no estas refiriendote al README sino al contenido de la pagina web, no?
