### ISSUE TITLE
Cambiar texto  de 'Telefonos de Emergencia'

### ISSUE THREAD

**Issue by jrmm22** [CodeandoMexico/terremoto-cdmx#248]
Siendo disenador, quiero cambiar el texto de la Seccion 'Telefonos de Emergencia' para mejorar la comunicacion con el usuario.

**Descripción del problema:**
Se propone el siguiente texto: "En estos momentos cualquier reporte puede marcar la diferencia. 
Reporta fugas de gas y agua, personas desaparecidas, incendios, entre otros, a los teléfonos de emergencia de tu ciudad:"

**Pasos para reproducir:**
N/A

**Resultado obtenido:**
N/A

**Resultado esperado:**
N/A

**Entorno:**
Todos

**Comment by astrocumbia** [comment]
Puedes subir mockup?

**Comment by jrmm22** [comment]
No tengo mockup positr0nix, el ticket se levanto basado en
https://docs.google.com/spreadsheets/d/1cWB6aSiESB6IUCn3DGrcqSUOIL62JLJjbWmFJu_Cs4w/edit#gid=46183942

Si puedes hacer una recomendacion, sera bienvenida.

**Comment by gilfranfer** [comment]
Es solo un cambio en el texto, porque los telefonos se van a hacer colapsables por estado
