### ISSUE TITLE
Agregar funcionalidad de Mostrar/Colapsar a la seccion de Telefonos de Emergencia (por Entidad)

### ISSUE THREAD

**Issue by jrmm22** [CodeandoMexico/terremoto-cdmx#249]
Siendo disenador, quiero habilitar la funcionalidad de mostrar/esconder para asi mejorar la presentacion de datos al usuario (en modo movil), y reducir el ruido visual en el Site.

**Descripción del problema:**
La seccion de Telefonos de Emergencia tiene una gran cantidad de informacion UTIL, por lo cual se recomienda que se agregue funcionalidad de Mostrar/Esconder para poder permitir al usuario navegar con mayor facilidad y mejorar su experiencia.
(De la misma manera, si es posible detectar su locacion actual y mostrar la informacion de esa entidad por default)

**Pasos para reproducir:**
N/A

**Resultado obtenido:**
N/A

**Resultado esperado:**
N/A

**Entorno:**
Principalmente Movil.

**Comment by anahiruiz** [comment]
Ya hice PR de una propuesta terminada para este issue(#249), acá una imagen:

![screenshot-2017-9-26 sismomx - informacion del sismo en la cdmx y el centro de mexico](https://user-images.githubusercontent.com/13294599/30842253-a23ccbec-a246-11e7-9099-dff00fcdaaaa.png)
