### ISSUE TITLE
Invertir botones Quiero y Necesito 

### ISSUE THREAD

**Issue by jrmm22** [CodeandoMexico/terremoto-cdmx#250]
Siendo disenador, quiero invertir la presentacion de 'Quiero' y 'Necesito' para mejorar la organizacion de las ligas con el contenido de la pagina.

**Descripción del problema:**
En la parte inicial de la pagina, se muestran las ligas de 'Quiero Ayudar' y luego 'Necesito Ayuda', sin embargo en la informacion se presenta primero la seccion de 'Necesito Ayuda' y luego la de 'Quiero Ayudar'. Se necesita cambiar la secuencia de los botones al inicio para mantener la coordinacion con el resto de la pagina.

**Pasos para reproducir:**
N/A

**Resultado obtenido:**
Botones invertidos con respecto a la informacion en la pagina.

**Resultado esperado:**
Botones e informacion en la misma secuencia. La informacion que puede resultar critica o time-sensitive ('Necesito Ayuda') debe mostrarse antes.

**Entorno:**
Todos.

**Comment by astrocumbia** [comment]
Voy trabajando en esto!
