### ISSUE TITLE
Usar separador 'section-line' consistentemente como separador

### ISSUE THREAD

**Issue by jrmm22** [CodeandoMexico/terremoto-cdmx#251]
Siendo desarrollador, quiero utilizar consistentemente el separador class='section-line' para mantener estilo en el codigo; manteniendo un solo estilo de separador.

**Descripción del problema:**
No se estan utilizando separadores antes de los class="subtitle pink", excepto antes de 'Otras Formas de Ayuda' y 'Bancos de Sangre'.
Debe de agregarse un
<hr class="section-line"> antes de cada seccion:
<div class>
<h2 class="subtitle pink">TEXTO</H2>
...
</div>

**Pasos para reproducir:**
N/A

**Resultado obtenido:**
Faltan separadores.

**Resultado esperado:**
Separadores horizontales entre cada <h2 class="subtitle pink">

**Entorno:**
Todos

**Comment by gilfranfer** [comment]
Done
