### ISSUE TITLE
Diseño: FAQ Títulos Bold

### ISSUE THREAD

**Issue by JPIglesias-Triangle** [CodeandoMexico/terremoto-cdmx#253]
Ya propusimos esto en el canal sismomx-grafico.

Queríamos ver si se pueden cambiar los títulos del FAQ (las preguntas) para que sean cómo los de otras secciones. Ahorita los del FAQ no son bold, pero en el resto de la página si.

Ojalá alguien no pueda ayudar. Les dejo un par de ss para que me entiendan mejor.

<img width="597" alt="captura de pantalla 2017-09-23 a la s 19 40 34" src="https://user-images.githubusercontent.com/24706093/30778286-6fb35a0c-a097-11e7-8936-ef1346a159d5.png">
^Si es bold el título 👍 
<img width="1036" alt="captura de pantalla 2017-09-23 a la s 19 37 58" src="https://user-images.githubusercontent.com/24706093/30778287-709a3da0-a097-11e7-9072-fb6fd827b29c.png">^No es bold el título 😢

**Comment by baezor** [comment]
Listo, ya tienen el mismo tag y clases! :D 
![screenshot 2017-09-24 00 27 37](https://user-images.githubusercontent.com/3989321/30779769-2f8ea92c-a0bf-11e7-8464-1a919bcb0e4d.png)
