### ISSUE TITLE
Revision general y planes a futuro ("Retrospectiva")

### ISSUE THREAD

**Issue by mxcoder** [CodeandoMexico/terremoto-cdmx#268]
Hola a todos

Sin duda es mucho lo logrado por este repo y todos los otros que se crearon durante la emergencia, la colaboración fue increíble.

Sin embargo, para que realmente perdure lo creado, sugiero realizar un análisis "Postmortem" que nos ayude a lo siguiente:

1. Establecer que herramientas funcionaron
1. Que problemáticas se solucionaron, con que eficiencia
1. Que problemas no pudieron ser solucionados
1. Que herramientas se duplicaron, y cual fue el motivo.
1. Que proyectos NECESITAN plantearse a largo plazo, incluso con ayuda de un canal oficial (como Protección Civil) y que mecanismos se pueden plantear para tener un control distribuido (que no pertenezcan o dependan de una sola entidad/persona)

Por proyecto también se requiere hacer un análisis parecido

1. Que salio bien
1. Que salio mal
1. Que partes quedan pendientes

El objetivo a largo plazo es prepararnos para desastres en el futuro. Estaremos listos?

**Comment by 2businessIntelligence** [comment]
Exacto, si queremos algo más grande eso debería unir a otros que realizaron esfuerzos buenos pero aislados y que no pudieron sumarse como mi grupo. Revisa nuestro análisis post mortem que publicamos a una semana www.planfuerzamexico.com y que optamos por dirigir a todos nuestros seguidores e informantes voluntarios al sitio de verificado19s. Yo propongo por ahora algo rápido porque hay muchas urgencias y debemos hacer planes si quieren varios seguir haciendo algo.

Posteriormente yo pongo el ITAM para hacer un foro serio invitando a personas de otros países a compartir sus experiencias y las nuestras. A los expertos en logística humanitaria y a los que puedan hablar de grupos que trabajaron en esta emergencia 19s

Vengan propuestas para realizar el primer encuentro. 

Seth

**Comment by mxcoder** [comment]
Gracias por aportar @2businessIntelligence y gracias por las propuestas. Creo que en los siguientes días deberíamos estar viendo que procede, pero espero que no pase demasiado tiempo y el potencial se diluya.

Por cierto, que otros grupos y repos se crearon con herramientas, tal vez podríamos invitarlos.

Yo conozco https://github.com/eldelentes/comoayudarmx de @eldelentes, pero pues queda a su consideración los pasos a seguir.

**Comment by eldelentes** [comment]
Hola chicos, aca les dejo mis opiones hasta ahora sobre todo lo sucedido y en especifico con comoayudar.

## Timing

Aprendí que algo imprecindible para estos casos es una respuesta casi inmediata, afortunadamente ya tenemos muchos proyectos o materiales listos para usar (A diferencia de esta ocación) pero es importante pensar en herramientas desplegables de manera casi inmediata a una situación similar.

Algo que ayudo mucho a nuestro proyecto fue la velocidad, el pensar en `¿Qué cpsas podemos hacer esta noche (El 19) nos ayudo a que 1.- El proyecto fuera lanzado a horas de lo sucedido y 2.- a que las personas tuvieran una herramienta sin esperar mucho tiempo.

## Fácil de usar

Ví muchos proyectos muy interesantes rondando por ahí, pero algo que note y que faltaba mucho era el tema del diseño, hay que recordar que cuándo se trata de sitios que van enfocados a gente de todo tipo, de respuesta inmediata e información es súper imporante tener un sitio de acceso rápido.

Por ejemplo, si yo al usuario le solicito que se registre, que me de su dirección, etc es muy dificil que esa persona proceda.

## Multi-lenguaje.

Mucho del tráfico que tuvimos fue internacional, en este tipo de acontecimientos personas de todo el mundo querian ayudar y era muy poco el material en inglés que existia. Nosotros nos tardamos mucho tiempo en implementar traducción lamentablente.

## Información Confiable

Afortunadamente los chicos de Verificando 19s se pusieron las pilas en estos momentos, pero antes de ese tema era y sigue siendo uno de los problemas mas grandes, el como podemos brindar información confiable y veraz.

## Una colaboración verdadera.

Algo que me gusto pero al mismo tiempo no tanto de todos los proyectos fue que todos querian hacer su propia plataforma, querían su propio sitio, querian hacer una app, etc.

En mi humilde opinión, creo que en estos casos lo importante es colaborar de una manera ordenada, si ya existe un proyecto que hace lo que tu querias hacer; no hagas un nuevo proyecto, suma a esta iniciativa.

Por otra parte, si ya tienes un proyecto, permite que otras personas puedan sumarse, no seas cerrado a decir "No, no puedes ayudar porque "x" tema.

## Dejar de lado los lenguajes, tecnicismos y experiencia.

Un problema que hubo en *comoayudarmx* fue al querer proponer como tener un backend como buenos desarrolladores todos queriamos meter cuchara, habia gente haciendo un backend en Rails, otros en React, otros opinando que era mejor usar PHP, etc...

En estos casos veo más importante el colaborar y aportar que el `Yo sé mucho de PHP y puedo hacer un backend más rápido`. Lo importante es definir prioridades y sumarse.

## Canal de comunicación

También algo que nos fallo a nosotros fue que al principio no teniamos un canal de comunicación al inicio.

Levantar Issues para todo. Así como comente que todo mundo buscaba hacer su propio Backend, esto no hubiera sido problema si cada vez que alguien iba a hacer un feature hubiera levantado un issue o leido los issues para saber que estaba sucediendo o el estatus.

## Redes Sociales nuestras mejores amigas

La idea de *comoayudarmx* muto de ser un sitio de información a que en Twitter funcionaramos como un intermediario en el intercambio de necesidades.

Conectamos a muchas personas que tenian necesidades en albergues, edificios, etc con personas que tenian material, herramientas, comida.

Definir un código de respuesta en redes sociales es súper importante.

## Relevos.

Un problema en estos casos es, por ejemplo, que yo estuve toda la semana desvelandome tratando de atacar todos los problemas, o luego uno necesita regresar a su "labor", es importante definir relevos de esfuerzo.

Quizás hoy no pudiste aportar nada a la plataforma, pero mejor espera y releva a los desarrolladores o gente de logistica en la semana que sigue.

Ire agregando más cosas conforme pase el día.

**Comment by angelamldz** [comment]
Comparto las opiniones de los compañeros en este issue. Sí, fue una primer experiencia (a la que en lo personal, lamentablemente llegué no tan de inmediato como quise) pero continúan los procesos y la generación de protocolos. Sigue: la consolidación de los sistemas de atención inmediata y el desarrollo de otros para el seguimiento del apoyo, y el monitoreo del estado de las comunidades.

Todo surgió de manera muy orgánica y eso opino yo le da legitimidad y valor.  Pero bueno, contestando las preguntas como haciendo la tarea (y en mi opinión personal):

Herramientas que funcionaron: Redes sociales, en el momento que se crearon espacios colaborativos. Pero sobre todo las verdaderas redes, esas formadas por lazos interpersonales que se crean entre individuos o grupos a base de confianza.
Creo que se solucionó el problema de "por dónde empezar?" en el momento en el que se creó el primer mapa colaborativo. No fue el más funcional, pero la idea de que lo primordial es **ubicar** las necesidades fue vital. Y no es porque me dedique a eso. Pero sí.
Qué problemas no pudieron ser solucionados: logística de transporte, atención inmediata  Herramientas que se duplicaron: bases de datos! motivo: ideas paralelas y diferentes métodos. 
Que proyectos necesitan plantearse a largo plazo: Una base lista y fácil de actualizar de las comunidades, y el estado en el que se encuentran. Se podría distribuir el control con una geobase de datos a la cual se tenga acceso por parte de diversos grupos coordinados. 

Bien: La "limpieza" gradual , cómo se fueron identificando las fuentes oficiales y la centralización de cierta información
Mal: Ver respuesta de @eldelentes 
Pendiente: Plan de seguimiento. Por favor, no lo soltemos.
