### ISSUE TITLE
Mapeo de zonas de riesgo

### ISSUE THREAD

**Issue by lcqAL** [CodeandoMexico/terremoto-cdmx#32]
El objetivo es comenzar a mapear zonas cuyas estructuras estén muy dañadasy tengan posible riesgo de derrumbe y alertar a las personas y redirigir esfuerzos ahí. Estaría alimentado de información ciudadana y de los análisis que las casas de arquitectura están haciendo.

**Comment by fernandosg** [comment]
@lcqAL Me interesa apoyar ¿cual sería la idea, crear un backend sencillo para recibir envíos por geolocalización? Se puede crear un front y enviarlo a firebase para almacenar la información, o hacer algo con algún framework rápido (rails) y guardar la información, montandolo en heroku.

Cualquiera de los dos, me apunto para desarrollarlo, no se si te referías a eso, o si ya haya una API(al menos un sitio para hacer scrapping) para obtener la información de casas con estructura dañada.

**Comment by MisaelSalcido** [comment]
También me interesaría apoyar

**Comment by lcqAL** [comment]
Chido, estaría bien ir haciendo el backend,  yo estoy mandando mensajes para que los que se han voluntariado a hacer levantamientos para que nos den datos georeferenciados y el nivel de daños

**Comment by JosueRo** [comment]
Hola a todos, nuestro compañero Leo (Openstreetmap y Estrategia Digital Nacional) lanzó este mapa colaborativo al que se le pueden añadir puntos georreferenciados y aparece un pequeño cuestionario. Chequen esto: https://github.com/leodc/mapeo_colaborativo

**Comment by fernandosg** [comment]
@lcqAL ¿Puedo hacer un pequeño backend en un repositorio aparte y ponerlo en estos comentarios para ver si pueden ocuparlo? Igual ya tengo un fork, haré una sección a parte para poder enviar la información de los lugares con js al backend que te menciono. Me basare en el cuestionario que menciona @JosueRo.

Me comentas porfa @lcqAL si esta bien mi idea de hacer un repo a parte y compartirlo en un fork el formulario para enviar la información.

**Comment by lcqAL** [comment]
Excelente @fernandosg vamos dándole

**Comment by lcqAL** [comment]
@MisaelSalcido te gustaría apoyar en bajar info ya sea scrapeando twitter o buscando voluntarios que handan levantando daños. Lo chido sería llegar a zonas como jojutla y ver cómo conseguir info de ahí

**Comment by abelhdez** [comment]
Hola, en que puedo ayudar? backend o en lo que se necesite

**Comment by lcqAL** [comment]
@Abelhdez te gustaría apoyar en bajar info ya sea scrapeando twitter o buscando voluntarios que andan levantando daños. Lo chido sería llegar a zonas como jojutla y ver cómo conseguir info de ahí. El objetivo es resaltar zonas donde este muy mal la situación y que se puedan redirigir esfuerzos allá

**Comment by MisaelSalcido** [comment]
@lcqAL Claro, pero veo que tienes 2 tablas diferentes, qué diferencia hay entre ellas?
EDIT:
Ya vi, me pondré a eso entonces.

**Comment by lcqAL** [comment]
tablas? @MisaelSalcido en donde, quien anda haciendo el backend es  @fernandosg

**Comment by Cacilie** [comment]
Hey, me encantaría ayudar en eso de bajar la info!

**Comment by abelhdez** [comment]
@lcqAL claro que si me gustaría, la información que recaude a donde se las hago llegar ?

**Comment by ricalanis** [comment]
estaría buenisimo si subes tu codigo y vas subiendo tus datos a datamx.io! :D

**Comment by lcqAL** [comment]
super @Garyi @Abelhdez, mándenlo a analisisyucatan.dt@gmail.com y de ahí hago la base y la subo a datamx @ricalanis va? si tienen mas compas estaría chido que se unieran por que si es una chambota

**Comment by MisaelSalcido** [comment]
@lcqAL Sorry, leí mal. Estaré enviando información a ese correo entonces.

**Comment by miguelsalazar** [comment]
Si necesitan crear un repositorio en Codeando México, me dicen. Sería más fácil tenerlo aquí para que no se quede en un GitHub individual y podamos sumar a muchos colaboradores.

**Comment by lcqAL** [comment]
Sale y vale, @fernandosg que andas en el backend

**Comment by RegulEsteban** [comment]
Me uno!! Qué necesitan?? en qué ayudo???

**Comment by lcqAL** [comment]
Hola @RegulEsteban Ahorita estamos en la recopilación de información. Buscar alguna forma de que la banda nos pase su ubicación y si le dijeron que su estructura esta en riesgo de derrumbarse para armar una base de datos. Contactarse con gente que esté haciendo análisis de estructura y que nos puedan brindar datos

**Comment by rxco** [comment]
Hola, voy llegando, necesitan ayuda con algo?
Aun están recopilando información? Tienen algún canal especifico en slack?

**Comment by fernandosg** [comment]
@miguelsalazar Tengo una propuesta de backend, ya la tenía hecha, pero revisando de nuevo hace unos mins vi ciertos atributos que no había añadido en los reportes de daños (me base en el repo de Leo, que comento @JosueRo). Hice un repositorio en mi perfil, pero como comentas Miguel, en un repo de codeandomexico les envió un pull request. 

Vi que añadieron LatLng, tenía ya pensado (e hice un pequeño código) para geolocalizar usando reversegeocoding (con la dirección completa) pero no lo añadí, ¿necesitan que en el formulario para añadir el reporte de daños se implemente eso? Lo haría en el transcurso del día.

Hice un repo en mi perfil, solo para pruebas, de un pequeño formulario para añadir reportes: https://fernandosg.github.io/jekyll-terremoto-cdmx/

El backend también lo subí a Heroku, solo para pruebas:

https://terremoto-zonariesgo-cdmx.herokuapp.com.

En la primer url que les pase puse un botón para abrir un registro de reportes de daños.

Si gustan, para que otros puedan ir avanzando, ya sea en el front o con ideas del backend, quería saber si me podían dar acceso al docs de los reportes, para vaciar el xls en el backend.

Saludos.

EDIT: Una disculpa, ya tengo el archivo editable del documento: https://docs.google.com/spreadsheets/d/1ijleBcHJH_3V2nbMeXTjH4hTDYsjcdodYvHqhTc8C8c/edit#gid=0, lo pasare al backend y les envió la url para que verifiquen los objetos que retorna.

**Comment by fernandosg** [comment]
Me latio mucho el diseño de este sitio https://ayuda-mx.com/personas, en la tabla de personas, y el filtrado, ¿estaría bien ponerlo así? o como mapa, en cuestión de las zonas reportadas.

**Comment by surielmx** [comment]
así está quedando más o menos el diseño que ya elaboraron en el canal de diseño.

**Comment by lcqAL** [comment]
Está con ganas @fernandosg . Ahorita la info para alimentar el sitio va a tardar en llegar pero me dijeron unos consultores que con mucho gusto nos daban lo que fueran recabando, solo que tienen muchísimo jale por que están evaluando muchas zonas y son pocos. Lo que hay es info que la banda subido en "Mapa de Edificios Derrumbados y Dañados por el Sismo del 19/09/2017" pero es sumamente ambiguo como para poder generar generar un mapa de riesgos confiable pero se podría ir haciendo un cale con esa info

**Comment by fernandosg** [comment]
@lcqAL Vientos, si esta bien, solo como prueba lo estaré vaciando, estaré al pendiente también para ver si tienen un repo de github para el backend e irlo subiendo.

@pokaxperia @lcqAL Que canales en slack están usando para comunicarse con respecto a este proyecto? Me comentas Mario que hay un canal de diseño.

**Comment by miguelsalazar** [comment]
@fernandosg: `#sismomx-diseño`

**Comment by fernandosg** [comment]
@miguelsalazar Gracias, ya entre al canal y al de sismomx-mapas para ver si puedo apoyarlos.

**Comment by EmmanuelGarces** [comment]
Hola. Soy desarrollador de funciones de visualizacion geográfica para Wolfram Research. Puedo apoyar en la visualización de histogramas en mapas, de gráficas de burbuja, de intensidades o en la limpieza de datos geográficos. Saludos !

![image](https://user-images.githubusercontent.com/32200763/30750194-5b7acb64-9f7b-11e7-838f-8d63ab1a977f.png)

![image](https://user-images.githubusercontent.com/32200763/30750399-06ff0a5e-9f7c-11e7-8750-8aa66517bba2.png)
