### ISSUE TITLE
Mejor vista de la sección de recursos en móviles

### ISSUE THREAD

**Issue by vincent1bt** [CodeandoMexico/terremoto-cdmx#37]
Cuesta trabajo visualizar la sección de recursos desde un telefono movil, la mayoria de personas que necesitan ayuda estan buscando infomación desde su celular, opino que lo mejor seria mover esa sección a otra pagina para poder extender todos los datos

**Comment by coderdiaz** [comment]
En lo que pueda ser de ayuda, veo que esta sección en ocasiones hace que se bloquee el navegador

**Comment by vincent1bt** [comment]
Hola buenas tardes, tenia la idea de con alguna libreria de javascript que leyera el formato csv traer los datos y acomomodar los mas importantes y abajo insertar el link para poder ir al documento completo, pero lo que veo es que la pagina esta hecha con jekyll, no sé si insertar un script en un documento md sea buena idea

**Comment by coderdiaz** [comment]
No necesariamente puede debe ser markdown, podríamos hacer un .html ese archivo si puede incluir el script y ahí hacer toda la funcionalidad que explicas

**Comment by coderdiaz** [comment]
Considero que está herramienta podría ayudar https://github.com/mholt/PapaParse

**Comment by vincent1bt** [comment]
Muy bien entonces voy a realizar el cambio y te puedo avisar para que lo veas y me digas que te parece

**Comment by coderdiaz** [comment]
@vincent1bt Perfecto, estaré pendiente

**Comment by vincent1bt** [comment]
Encontre un problema con el archivo de google docs, solo permite visualizar los datos pero no editar , tampoco puedo usarlo porque no lo reconoce como formato csv

**Comment by tlacoyodefrijol** [comment]
Lo que queremos es visualizar sólo una parte de las spreadsheets?

**Comment by vincent1bt** [comment]
@tlacoyodefrijol así es, para que se pueda mostrar mejor en los telefonos y no tarde tanto en cargar el documento completo

**Comment by BrunoGGM** [comment]
Ya se esta trabajando en esto?

**Comment by vincent1bt** [comment]
@BrunoGGM no estoy seguro si en el rediseño de la pagina lo esten implementando, yo intente hacerlo pero no puedo acceder al csv de google docs para poder extraer la información

**Comment by tlacoyodefrijol** [comment]
Las actualizaciones de diseño se están haciendo en #83, como debería de quedar el diseño está en #85. @vincent1bt @BrunoGGM
