### ISSUE TITLE
Otro mapa de daños

### ISSUE THREAD

**Issue by pel-daniel** [CodeandoMexico/terremoto-cdmx#4]
Hola, 
Encontre este otro mapa de daños https://www.google.com/maps/d/viewer?mid=1_-V97lbdgLFHpx-CtqhLWlJAnYY&ll=19.423843561361952%2C-99.15851186345913&z=14 tiene bastantes views, saben si hay forma de ver quien lo creo para unificar esfuerzos ??

**Comment by miguelsalazar** [comment]
Gracias, lo agregamos y movemos a #9 .
