### ISSUE TITLE
Mapa #AyudaCDMX

### ISSUE THREAD

**Issue by jorandradefig** [CodeandoMexico/terremoto-cdmx#44]
[#AyudaCDMX](https://bit.ly/AyudaCDMX)

Derrumbes, albergues, hospitales y voluntariado.

**Comment by miguelsalazar** [comment]
¿Cuál es el accionable de este issue?

**Comment by elbaloo** [comment]
#49 ya esta merged, segun yo ya se puede cerrar esto
