### ISSUE TITLE
Optimizar carga para móviles del landing

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/terremoto-cdmx#48]
El website está cargando demasiado lento en slow connections o fuera de wifi. Debe ser por los spreadsheets que están embebidos

**Comment by gilfranfer** [comment]
El menú de navegación superior no responde adecuadamente en móvil. Supongo tiene que ver con la carga lentes de la página.

**Comment by arochamaria** [comment]
Voy a trabajar en la optimización de la versión móvil de la Landing. Alguien mas esta trabajando en esto en algun branch?

**Comment by gabelula** [comment]
Hay un PR por aprobarse que hace algo: https://github.com/CodeandoMexico/terremoto-cdmx/pull/60

**Comment by nokrosis** [comment]
Supongo que ya están trabajando en el issue, así que agrego algunos punto a considerar par mejorar carga en móvil.

- Mover mapas embebidos a secciones interiores, para evitar cargar todo en el home
- No me parece necesario que se vea bonito, sino que sea útil, así que se puede prescindir de google fonts.
- No creo que tenga tanta relevancia, pero hay 2 códigos de analytics
- Hay que aumentar la altura de los botones del menú, para darle usabilidad, ya que quedan muy pequeños para un dedo. (Altura mínima de 35px)
- Las imagenes de fondo son innecesarias

**Comment by israads** [comment]
Yo puedo trabajar en esto, avísenme si aun no está

**Comment by gabelula** [comment]
@israads Podes chequear que mas falta para terminar este issue?

**Comment by israads** [comment]
@gabelula correcto, ahora reviso que más puedo hacer para optimizar

**Comment by dbautistav** [comment]
Los cambios que se vayan incorporando deberían considerar que sean útiles para todo tipo de usuarios, siguiendo principios de accesibilidad. Aquí algunos recursos:

- [A11y Command-line Tools](https://addyosmani.com/a11y)
- [The A11Y Project](http://a11yproject.com)
- [web accessibility](https://wa11y.org)

**Comment by israads** [comment]
Los tiene y se estáoptimizada la página, creo que este se puede cerrar por ahora mientras se le agregan más cosas

**Comment by tlacoyodefrijol** [comment]
enterado @israads
