### ISSUE TITLE
Mapa de solicitudes de ayuda de Facebook

### ISSUE THREAD

**Issue by pel-daniel** [CodeandoMexico/terremoto-cdmx#5]
Facebook tiene una página bastante útil para señalar dentro de un mapa si se necesita ayuda en una zona o personas que están dispuestas a ayudar.
Creo sería útil añadirlo https://www.facebook.com/safetycheck/rabosa-puebla-mexico-earthquake-sep19-2017/?type=request&category=volunteers

**Comment by miguelsalazar** [comment]
Lo agrego a #9 .
