### ISSUE TITLE
Agregar proyectos al README

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/terremoto-cdmx#50]
> BanFake News https://github.com/RZEROSTERN/banfakenews PHP, Yii
> API para centros de acopio https://github.com/Skycatch/acopio-api JS, Hapi
> comoayudar.mx backend https://github.com/ComoAyudarMX/CAMbackend JS, express
> http://sismomexico.org https://github.com/CodeandoMexico/terremoto-cdmx Jekyll, HTML, CSS, ruby
> Encontrar las necesidades más prioritarias por zona para enviar ayuda y notificar https://github.com/civica-digital/quake-relief-cdmx/commits/master Ruby on Rails 5.0 
> send sms alerts for the earthquake in mexico https://github.com/denialtorres/SMS-ALERTS Ruby on Rails 4.2
> Herramienta para el reporte ciudadano https://github.com/leodc/mapeo_colaborativo JS, express, socket.io

**Comment by gabelula** [comment]
Hay gente en el slack de estos proyectos?

**Comment by gabelula** [comment]
PR https://github.com/CodeandoMexico/terremoto-cdmx/pull/52

**Comment by miguelsalazar** [comment]
No respondí a tiempo, pero sí, todos tienen un owner que está en Slack.
