### ISSUE TITLE
Visualización Mobile

### ISSUE THREAD

**Issue by gustavobn** [CodeandoMexico/terremoto-cdmx#56]
- Tenemos problemas de visualización en mobile:
  - Menús
  - Columnas
  - Navegación General

<img width="243" alt="screen shot 2017-09-20 at 19 16 17" src="https://user-images.githubusercontent.com/1815091/30673380-4903b1d8-9e38-11e7-9b64-aba16ff383c0.png">

- Necesitamos un refactorizado de un front que tenga experiencia con `skeleton` o algún framework similar. Creo que es indispensable ya que para ayudar la gente consultará el sitio en dispositivos móviles.

**Comment by canito0890** [comment]
Hay unas divisiones invisibles ocupando espacio rompiendo con el estilo responsivos en móviles.
