### ISSUE TITLE
Google spreadsheets API para mejorar scrolling con los .csv

### ISSUE THREAD

**Issue by nicandromts** [CodeandoMexico/terremoto-cdmx#57]
Pienso usar esta guia para implementar mejoras en el scrolling de las tablas
https://developers.google.com/sheets/api/quickstart/js

_feel free to join_

**Comment by NotZombieFood** [comment]
@nicandromts cómo te apoyo? :)

**Comment by nicandromts** [comment]
la idea es usar opendatasoft e implementar las funciones que aparecen ahi para usarse en el spreadsheet

**Comment by nicandromts** [comment]
aqui esta el link de la API https://cdmx.opendatasoft.com/explore/dataset/hospitales-cdmx/api/?location=10,19.36964,-99.14952

**Comment by xiam** [comment]
En este branch tengo una prueba de concepto https://github.com/CodeandoMexico/terremoto-cdmx/tree/drafting-opendatasoft, el query que estoy usando es el de hospitales. Se están exportando datos de otros datasets.

![screen shot 2017-09-20 at 20 05 43](https://user-images.githubusercontent.com/385670/30674749-d20d30c2-9e41-11e7-859c-1bb44a6e0556.png)

**Comment by nicandromts** [comment]
SI, ESO ES EXACTAMENTE LO QUE SE DEBE HACER

**Comment by xiam** [comment]
Sería genial ayuda en lo siguiente:

* Estoy usando `fetch`, ¿podemos usar un polyfill para soporte a otros browsers?
* Falta crear callbacks para llenar las secciones, la que están armando ahorita es la de centros de acopio por estados.

**Comment by nicandromts** [comment]
dejame checarlo 
gracias

**Comment by xiam** [comment]
hola @nicandromts, pudiste avanzar?

**Comment by NotZombieFood** [comment]
Me avisan sino para darle después de comer

**Comment by nicandromts** [comment]
sorry broders estoy atorado con una bronca de mi chamba. 
vayanle pegando, me conecto en la noch e
