### ISSUE TITLE
Documentos y bases de datos colaborativas

### ISSUE THREAD

**Issue by pel-daniel** [CodeandoMexico/terremoto-cdmx#6]
Aca hay otro documento colaborativo en el que hay bastante gente ayudando https://docs.google.com/spreadsheets/d/1a-rZqtPUvHn-73sZEb7Epn4R9ouTiMfjPOysB-4hLYA/edit#gid=0. Seria bueno coordinar esfuerzos.

**Comment by aornelas** [comment]
+1!

en lo que las fusionan, hice http://bit.ly/rescatecdmx para compartir esa lista más fácil... ya que las junten, puedo redirigirlo

**Comment by miguelsalazar** [comment]
Gracias, los estoy agregando al website.

**Comment by miguelsalazar** [comment]
Cambié el título del issue para que agreguen aquí todos los documentos y bases de datos colaborativas que encuentren.

**Comment by Plus17** [comment]
Lista de recursos (Centros de acopio, albergues, coordinación, donativcos, etc. ):
https://docs.google.com/spreadsheets/d/1Al5AoqF0_Dj-QyWi4LDltu4twCQaMcFUU19UoXDbC4o/edit#gid=0

**Comment by gustavobn** [comment]
#f1b00aa

**Comment by rocioalmangui** [comment]
Hola! 
Estoy juntando las listas de recursos que pueden servir para el aftermath. Voy a corroborar y preguntar a los contactos que vengan en las listas si pueden seguir ofreciendo servicios gratuitos a mediano plazo y con qué condiciones. ¿En cuál creen que sea mejor basarme? En slack soy Rocio Denver
