### ISSUE TITLE
Rediseño de sitio web

### ISSUE THREAD

**Issue by coderdiaz** [CodeandoMexico/terremoto-cdmx#62]
Se llevará a cabo la versión mejorada del sitio a la versión proporcionada por el equipo de diseño.
Este considerará todo lo correspondiente: 
- Fuentes.
- Colores.
- Versión móvil.
- Secciones.

### Diseño
https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by arochamaria** [comment]
Genial, necesitan ayuda para la maqueta?

**Comment by arochamaria** [comment]
@nokrosis comento: 

- Mover mapas embebidos a secciones interiores, para evitar cargar todo en el home
- No me parece necesario que se vea bonito, sino que sea útil, así que se puede prescindir de google fonts.
- No creo que tenga tanta relevancia, pero hay 2 códigos de analytics
- Hay que aumentar la altura de los botones del menú, para darle usabilidad, ya que quedan muy pequeños para un dedo. (Altura mínima de 35px)
- Las imágenes de fondo son innecesarias

**Comment by ghost** [comment]
quien esta aportando en esto?  yo quiero aportar con esta parte

**Comment by coderdiaz** [comment]
@tavorazo yo lo estoy trabajando, estoy por terminar la base

**Comment by ghost** [comment]
ok, te parece si subes la base y te ayudo con una parte

**Comment by almeidatercero** [comment]
si necesitan ayuda con maquetación/diseño me apunto!

**Comment by coderdiaz** [comment]
@tavorazo si, solo que creo que vamos a tener que esperar un poco en que no se muevan las secciones porque hay que reestructurar un poco los posts

**Comment by Nifled** [comment]
Yo me apunto para ayudar tambien! Hay algun grupo de Slack donde esten trabajando sobre esto?

**Comment by HzJavier** [comment]
@Nifled checa http://slack.codeandomexico.org/ el [Readme](https://github.com/CodeandoMexico/terremoto-cdmx)

**Comment by coderdiaz** [comment]
Yo por el momento lo voy a dejar hasta aquí, alguien clone el proyecto y trabaje sobre la rama **feature/redesign-website-ui**.

Cabe recalcar que estamos trabajando sobre http://getskeleton.com/.

Gracias :)

**Comment by coderdiaz** [comment]
Hay que realizar una subrama de esta para empezar a colaborar y solo ir haciendo merge de cada una de las secciones que vayan generandose en PR apuntando a esta rama, para evitar problemas posteriormente.

Saludos.

**Comment by jorandradefig** [comment]
De acuerdo @coderdiaz. Saludos.

**Comment by Crowly34** [comment]
¿Cómo se están dividiendo el trabajo en esta parte? Yo puedo ayudar, ya cloné el proyecto quiero ir viendo si tienen los task pendientes en algún archivo, estoy al pendiente de este thread.

**Comment by coderdiaz** [comment]
@Crowly34 no, no se tienen tareas correspondientes, tendrían que ponerse de acuerdo en el canal de slack, lo único que tienen que ver es que dos personas no estén haciendo lo mismo

**Comment by coderdiaz** [comment]
Ahorita solo que hay que acoplar todas las secciones que ya estaban al nuevo estilo, ir fusionando las ramas a esta en específico y posteriormente colocar los nuevos cambios de master aquí y nuevamente adecuar.

**Comment by Crowly34** [comment]
Eso estoy viendo en el canal justamente, yo creo vamos a hacer un documento, gracias igual.

**Comment by Crowly34** [comment]
¿Esta todo en feature/redesign-website-ui? para clonar de ahí y revisar que es lo que falta con respecto al diseño de arriba.

**Comment by coderdiaz** [comment]
si, todo esta ahí, si gustas hago un recuento de lo que falta y pongo la lista acá para que la vayan viendo, te parece?

**Comment by Crowly34** [comment]
Facilitaría la chamba bastante,  gracias!

**Comment by coderdiaz** [comment]
- [ ] Secciones del sitio (Estas pueden ser trabajadas una a una para evitar problemas de que dos personas trabajen en lo mismo).
- [ ] Estilos globales.
- [ ] Menu header para dispositivos móviles.
- [ ] Footer con el nuevo diseño.
- [ ] Agregar scripts del template original.
- [ ] Adaptación a versión móvil.
- [ ] Adaptación de publicaciones a nueva versión.

**Comment by coderdiaz** [comment]
@Crowly34 creo que estas serían todas las tareas que se me ocurren que faltan.

**Comment by Crowly34** [comment]
Gracias!

**Comment by Crowly34** [comment]
@arochamaria, @tavorazo, @HzJavier, @almeidatercero, @jorandradefig, si alguno sigue reportense en slack, estamos sacando los tasks de aquí como issues, solamente que estamos especificando más las tareas para que sea mas sencillo trabajar cada quien en un issue.

**Comment by arochamaria** [comment]
@Crowly34 Yo estoy trabajando en la parte rosada de los botones de ayuda podes crear un issue para asignarmelo? Gracias!

**Comment by Crowly34** [comment]
@arochamaria #72

**Comment by Crowly34** [comment]
Solo que no sé asignar issues de Github, recuerden hacer un branch del que tiene este issue y no trabajar sobre este, (será como nuestro master).

**Comment by Crowly34** [comment]
@coderdiaz ¿no estaría un poco más veloz la página si en vez de los recursos embebidos pusieramos links externos a los documentos? veloz y un poquitín mas agil visualmente

**Comment by givanse** [comment]
@Crowly34 Me parece ese thread/issue esta siendo resuelto aquí https://github.com/CodeandoMexico/terremoto-cdmx/issues/48

**Comment by coderdiaz** [comment]
@givanse ese issue sólo es una mejora, este issue corresponde a todo el nuevo diseño

**Comment by Crowly34** [comment]
@givanse excelente! entonces evito esa sección y prosigo, cualquier cosa con los issues que marco, es perfectamente válido correcciones y apuntes, yo solo los pongo porque vi muchas manos y poco orden para hacer las cosas sin estorbarnos.

**Comment by Crowly34** [comment]
@coderdiaz de ese issue es importante sacar algunas mejoras al diseño en cuestiones de velocidad (como quitar las imágenes y pasar algunos recursos a otras secciones), estaría importante ver si hay alguien de diseño que nos pueda apoyar en tiempo real con lo que los compañeros estan trabajando y hacer todo esto junto, yo puedo encargarme de la comunicación de issues dentro de el website si lo desean así.

**Comment by coderdiaz** [comment]
@Crowly34 yo de hecho iba a realizar todo el diseño pero ya estoy un poco cansado, entonces ahorita por eso deje de aplicarlo, creo que esto sale en un día y la prioridad era salir con el diseño, ya que mover las cosas despues es mucho mas sencillo, ya que si ahorita queremos hacer todo no vamos a salir y se va a seguir pateando la tarea

**Comment by navarrorc** [comment]
Se ha creado algún channel en slack para este esfuerzo de redesign? Me gustaría ayudar pero tengo que ver donde todo mundo está para no repetir trabajo. Gracias.

**Comment by Crowly34** [comment]
@navarrorc Estamos en el de desarrollo, pero si ingresas a todos los issues que son parte del redesign algunos estan asignados y algunos no.

**Comment by dbautistav** [comment]
Así como [se podrían mover los mapas a secciones interiores](https://github.com/CodeandoMexico/terremoto-cdmx/issues/62#issuecomment-331030369) para evitar cargar todo en la página principal, se podría hacer los mismo con los spreadsheets.

Además, se podrían crear algunas vistas ([_views_ como en sql](https://en.wikipedia.org/wiki/View_(SQL))) a partir de filtros "inteligentes" (algo como: ciudad, delegación ( #12 ); pestañas/hojas del doc), usando [fusiontables](https://support.google.com/fusiontables/answer/171206?hl=en).

Quizá relacionado con #57.

-----

Ahora que reviso [la maqueta](https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01) veo que dejaron fuera los spreadsheets. Esto es intencional o no se han agregado todavía?

**Comment by coderdiaz** [comment]
@dbautistav lo que comentas, se puede hacer con liquid de Jekyll usando variables en las publicaciones y hacer un where en los posts como si fuese un filtrado.

**Comment by tlacoyodefrijol** [comment]
@coderdiaz ya está implementado el diseño en jekyll. Hay issues nuevos

**Comment by coderdiaz** [comment]
@tlacoyodefrijol va, en la tarde noche tengo tiempo de retomarlo, si hay issues les doy con todo, seguiré atento 👍
