### ISSUE TITLE
Nuevas Features Ban Fake News

### ISSUE THREAD

**Issue by RZEROSTERN** [CodeandoMexico/terremoto-cdmx#63]
Unámonos en el esfuerzo de erradicar las noticias falsas en Internet.

Ban Fake News está abierto a features y colaboración. Se requieren desarrolladores con experiencia en PHP.
Igualmente si se tiene alguna propuesta de diseño gráfico, UX y UI, bienvenidos sean.

Cualquier duda o comentario, estoy a sus ordenes en el Slack en el canal #sismomx-fakenews.

**Comment by miguelsalazar** [comment]
@RZEROSTERN: Agrega el accionable de al README, bajo las categorías de Desarrollo y Diseño y linkea ya sea a este issue con información más extendida, o a issues concretos si ya los tienen definidos.

**Comment by 0nix** [comment]
+1

**Comment by ghost** [comment]
en que podemos ayudar? existe otro repo o en este mismo? @RZEROSTERN

**Comment by tlacoyodefrijol** [comment]
Cerrando Issue, si quieren aportar @tavorazo pueden revisar en https://github.com/RZEROSTERN/banfakenews/issues
