### ISSUE TITLE
Crear hyperlinks a mapas

### ISSUE THREAD

**Issue by salmedina** [CodeandoMexico/terremoto-cdmx#65]
Crear hyperlinks a cualquier tipo de mapas (Google, Apple, OpenMaps, etc) de los textos que se refieren a una ubicación como los centros de acopio, bancos de sangre, etc.

**Comment by gabelula** [comment]
@salmedina Podemos cerrar este issue?

**Comment by salmedina** [comment]
Perfecto! Gracias!

**Comment by omero** [comment]
Chicos antes de cerrar el issue saben que onda con `Hospital ABC de Constituyentes` ese no tiene hiperlink pero tengo confusion si es lo mismo que `Hospital ABC Observatorio` sean lo mismo

**Comment by salmedina** [comment]
Creo que erróneamente se le dice Constituyentes por su cercanía con esa avenida. Alguien podría confirmar?

**Comment by omero** [comment]
#sismomx-contenido no me responde aún pero creo que es el unico punto a aclarar para cerrar este issue

**Comment by rockarloz** [comment]
https://github.com/CodeandoMexico/terremoto-cdmx/pull/71

Se dejan ambos con la misma direccion , baso en esto http://www.abchospital.com/directorio-medico/

**Comment by omero** [comment]
Veo las ubicaciones en orden creo que ahora si podemos cerrar el issue @salmedina
