### ISSUE TITLE
Rediseño de sitio web / Footer con el nuevo diseño.

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#69]
## Implementar el footer con el rediseño de la plataforma.

**Diseño**
https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by luisejrobles** [comment]
hola que tal @Crowly34 , ya hay gente trabajando en ello?

**Comment by Crowly34** [comment]
Que tal @luisejrobles! aún no, yo estoy subiendo los tasks del issue general (#62), si quieres asignatelo, clona la rama  feature/redesign-website-ui y si no tuviste problema para servir jekyll con el proyecto, dale! estamos en el canal de Slack por si quieres mas rápido, estoy comparando lo que hay en la rama con lo que esta en el diseño para sacar más issues, por si me tardo en contestar acá

**Comment by luisejrobles** [comment]
vale, trabajaré en ello @Crowly34

**Comment by givanse** [comment]
los admins del repo son los que deben poner los assignees ~, o cambien el setting para que lo pueda hacer uno mismo~

no puedo creer que ese feature no exista

**Comment by luisejrobles** [comment]
que sugieres @givanse , me espero?

**Comment by Crowly34** [comment]
@luisejrobles "Por ahora agrega un comentario con la persona que va a estar haciendolo." dicen en el Slack, despues de la explicación anterior, así que a darle!

**Comment by Crowly34** [comment]
asignee: @luisejrobles

**Comment by Crowly34** [comment]
#85 ya hizo gran parte del sitio, espero aprobación para trabajar sobre sus avances y continuar desde ahí
