### ISSUE TITLE
 Rediseño de sitio web / Menu header para dispositivos móviles.

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#70]
Comportamiento responsivo para el menú en móvil.

**Diseño**

https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by givanse** [comment]
Hay target visual para esto? O el que lo implementa decide XD?

**Comment by coderdiaz** [comment]
@givanse Ahí esta el diseño base, hay que implementar una opción, posteriormente el equipo de diseño puede mejorar el UX, la prioridad es salir con ese diseño

**Comment by Crowly34** [comment]
asignee: @Nifled

**Comment by Crowly34** [comment]
@givanse ¿puedes trabajar en él? @coderdiaz inició el issue y pues fue él el que hizo muchas de las implementaciones, pero estaría poca madre que estuviera ya fundamentado al salir.

**Comment by Nifled** [comment]
https://github.com/CodeandoMexico/terremoto-cdmx/pull/90

**Comment by Crowly34** [comment]
#85 ya hizo gran parte del sitio, espero aprobación para trabajar sobre sus avances y continuar desde ahí
