### ISSUE TITLE
Rediseño de sitio web / banner de Quiero ayudar!/Necesito ayuda

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#72]
Banner con botones de Quiero ayuda/necesito ayuda

***Diseño***

https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by Crowly34** [comment]
asignee: @arochamaria

**Comment by arochamaria** [comment]
Ya tenes esto en pull request @Crowly34 con nombre feature/seccion-botones checatelo!

**Comment by Crowly34** [comment]
Gracias @arochamaria yo no puedo aceptar los pull requests porque no soy parte del repo, solo ayudaba a organizarnos, esperemos a ver si se acepta.

**Comment by Crowly34** [comment]
#85 ya hizo gran parte del sitio, espero aprobación para trabajar sobre sus avances y continuar desde ahí
