### ISSUE TITLE
Rediseño de sitio web / Diseño general de textos

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#73]
Agregar fuentes pertinentes para todas las secciones en el estilo global, delimitar el estilo para los títulos de sección, subtítulos, párrafos etc.

***Diseño***

https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by givanse** [comment]
Le preguntaría a los diseñadores si esto requiere un custom font. De ser así, sería mejor evitarlo. Un requerimiento de alta importancia es que consuma la menor cantidad de datos.

**Comment by NotZombieFood** [comment]
@givanse están usando Roboto, así que si involucra una descarga

**Comment by coderdiaz** [comment]
@givanse @NotZombieFood Es Roboto Mono y ya esta cargada la fuente en el proyecto con google fonts

**Comment by Crowly34** [comment]
@coderdiaz hay que cambiar por una fuente que se pueda cargar en el navegador para utilizar la menor cantidad posible de datos y que sea agil visual y funcionalmente

**Comment by givanse** [comment]
assignee: @givanse
