### ISSUE TITLE
Rediseño de sitio web / cambiar fuente por web-safe

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#74]
Cambiar la fuente descargada por una fuente que se pueda utilizar desde el navegador propio

tentativa: Arial, Helvetica, sans-serif

**Comment by givanse** [comment]
supersede https://github.com/CodeandoMexico/terremoto-cdmx/issues/73, no?

assignee: @givanse

**Comment by Crowly34** [comment]
@givanse Si ¿lo borro?

**Comment by givanse** [comment]
Solamente hay que cerrar el issue.

**Comment by Crowly34** [comment]
Esperaremos entonces, yo puedo abrir issues mas creo que no cerrarlos.

**Comment by givanse** [comment]
Este hay que abrirlo.

El que hay que cerrar es #73

**Comment by givanse** [comment]
~https://github.com/CodeandoMexico/terremoto-cdmx/pull/81~

**Comment by NotZombieFood** [comment]
Este ya quedó
