### ISSUE TITLE
Rediseño de sitio web / Links del header no estan mandando a ancla.

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#76]
Redireccionar las ligas del header para que te envíen hacia un ancla.

**Comment by astrocumbia** [comment]
Puede ser un poco más especifico con el issue ?

**Comment by Crowly34** [comment]
#85 dice que ya hizo gran parte del sitio, espero respuesta del estado de su proyecto para no trabajar doble.
