### ISSUE TITLE
Rediseño de sitio web / Sección quiero ayudar

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#79]
Hacer sección necesito ayuda con el titulo y sus subtítulos, tomar en cuenta que el estilo general del texto **ya se está trabajando**, después capturar la información actual en la sección.

Sub-secciones de quiero ayudar:

* Donar sangre
    1. Requisitos
    2. Bancos de sangre CDMX

* Ayudanos a tener más información
    1. mapea con OPENSTREETMAP
    2. Colabora agregando centros de acopio y ayuda a nuestra base.

* Dona en especie
    1. Medicamentos /Curación
    2. Herramientas
    3. aseo personal
    4. Viveres

* Dona depositanto
* Otras formas de donar
* Contribuye con código

La imagen se sustituye por otra franja rosa como la de "necesito ayuda" por cuestiones de agilidad y uso de datos de la página.

Diseño base

https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by Crowly34** [comment]
asignee: @crowly34

**Comment by Crowly34** [comment]
#85 ya hizo gran parte del sitio, espero aprobación para trabajar sobre sus avances y continuar desde ahí

**Comment by tlacoyodefrijol** [comment]
Cerramos este entonces @Crowly34 ?

**Comment by Crowly34** [comment]
@tlacoyodefrijol Si tienes oportunidad me gustaría que se apruebe el pull request de ahí para ya cerrar todos estos y trabajar sobre de ese, también para ir trabajando en moverlo a master.

No se quien pueda apoyarnos con la aprobación del pull request.

**Comment by tlacoyodefrijol** [comment]
podemos pasarlo al slack? Porque seguiremos con jekyll. Es más bien aprobar el diseño de #85 para pasar lo que tenemos a ese diseño
