### ISSUE TITLE
Rediseño de sitio web / FAQ

### ISSUE THREAD

**Issue by Crowly34** [CodeandoMexico/terremoto-cdmx#80]
Agregar banda rosa en vez de imagen a la parte de preguntas frecuentes

***Diseño base***
https://www.figma.com/file/WWr0IfDxJLIn26YuOYOTuQlz/cmx_sismomx_website_01

**Comment by jorandradefig** [comment]
Tomo este (jorandradefig).

**Comment by Crowly34** [comment]
Asignee:@jorandradefig

**Comment by Crowly34** [comment]
@jorandradefig no han aceptado mi pull request pero propuse <div class="section__separator"></div> para la franja y ya está con estilo, no es mucho lo que queda.

**Comment by jorandradefig** [comment]
Ah pues dale @Crowly34, no problem. 🤙🏼

**Comment by israads** [comment]
como van con este? que falta?

**Comment by Crowly34** [comment]
#85 ya hizo gran parte del sitio, espero aprobación para trabajar sobre sus avances y continuar desde ahí
