### ISSUE TITLE
Mapas

### ISSUE THREAD

**Issue by rockarloz** [CodeandoMexico/terremoto-cdmx#9]
https://gobiernofacil.com/herramientas/centros-de-acopio-en-puebla

**Comment by miguelsalazar** [comment]
De @pel-daniel:
https://www.google.com/maps/d/viewer?mid=1_-V97lbdgLFHpx-CtqhLWlJAnYY&ll=19.423843561361952%2C-99.15851186345913&z=14 

> Facebook tiene una página bastante útil para señalar dentro de un mapa si se necesita ayuda en una zona o personas que están dispuestas a ayudar.

https://www.facebook.com/safetycheck/rabosa-puebla-mexico-earthquake-sep19-2017/?type=request&category=volunteers

**Comment by miguelsalazar** [comment]
Cambié el título del issue para agregar todos los mapas colaborativos que encontremos.

**Comment by Plus17** [comment]
Ubicación de áreas criticas:
https://www.google.com/maps/d/viewer?hl=en&mid=1PwJrCIjz5PNfKAFrY-EX-iEkWH8&ll=19.276060869131236%2C-98.73599060000004&z=10

**Comment by jclopeztavera** [comment]
Hola, del [documento](https://docs.google.com/spreadsheets/d/1ijleBcHJH_3V2nbMeXTjH4hTDYsjcdodYvHqhTc8C8c/edit#gid=0) de mapeo colaborativo en Google Drive que está circulando, hice este R script para:

1.  Obtener los datos del documento
2. Limpiarlos y procesarlos
3. Obtener coordenadas (Google API) de observaciones sin coordenadas
4. Mapearlo usango ggmap + ggplot2

https://gist.github.com/jclopeztavera/c59f595da6553dbf26cd4c2f837a9b70

**Comment by gabelula** [comment]
Excelente! Tal vez podemos agregar un folder para scripts que tenga scripts de limpieza de datos y agregamos el tuyo.

**Comment by miguelsalazar** [comment]
Si hay más mapas, compartirlos en `#sismomx-mapas`.
