### ISSUE TITLE
Inventario y Distribución de Víveres 

### ISSUE THREAD

**Issue by xWazzo** [CodeandoMexico/terremoto-cdmx#92]
Hay mucho inventario en los centros de acopio, pero no se sabe cuánto ni qué ni dónde se ocupa.

Necesitamos generar la solución con algo ya existente o crearlo.

**Comment by gilfranfer** [comment]
Ya estan trabajando en eso:
https://github.com/Skycatch/acopio-api

Puedes seguir la conversacion en #sismomx-acopio-api
