### ISSUE TITLE
Mejorar SEO del sitio

### ISSUE THREAD

**Issue by huhgawz** [CodeandoMexico/terremoto-cdmx#93]
Algun experto en [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization) que desee colaborar a posicionar el sitio dentro de los primeros resultados de busqueda de los principales buscadores?

**Comment by huhgawz** [comment]
Quizas sea buena idea esperar a que el sitio redisenado sea liberado para trabar de lleno en este issue

**Comment by marianagh** [comment]
Hacen falta los tags de Open Graph 

Hace falta tener esto en las tags:
![image](https://user-images.githubusercontent.com/14349414/30707968-f992f60c-9eb1-11e7-85b9-c4e5a95ec3c8.png)

Me estaba apoyando con el plugin [Jekyll SEO Tag](https://jekyll.github.io/jekyll-seo-tag/) pero no lo pude probar aqui un ejemplo. 
Lo dejo como referencia.

```

   <!-- Meta Tags -->
<meta property="og:title" content="{{site.tittle}}" />
<meta property="og:locale" content="es_MX" />
<meta property="og:description" content="{{site.description}} " />
<link rel="canonical" href="http://sismomexico.org" />
<meta property="og:url" content="http://sismomexico.org" />
<meta property="og:site_name" content="Jekyll SEO Tag" />
<meta name="twitter:card" content="summary">

```

**Comment by paco-leyva** [comment]
El SEO del sitio en general es bueno, para mejorarlo un poco además de lo que mencionaron arriba agregaría: 

- Solo puede haber un H1 en cada página, como esta es un landing solo puede haber uno en toda la página, los otros títulos tendrían que cambiarse por H2, H3, etc.
- Agregar más keywords, encontré que estas pudieran ser de ayuda: CRUZ ROJA, PROTECCIÓN CIVIL, CIUDAD DE MÉXICO, MEXICO CITY, HOSPITAL, FUGAS, BANCOS DE SANGRE  y si es posible agregarlas en los títulos y en <title> del sitio y <description>. 
-Generar favicons para la mayor parte de dispositivos, este sitio es de mucha ayuda: http://www.favicomatic.com/
-Si es posible, poner el sitio bajo HTTPS, para no comprar un certificado se puede usar: https://letsencrypt.org/
- Agregar robots.txt y sitemap.

**Comment by huhgawz** [comment]
gracias @paco-antley trabajare ahora mismo en crear `robots.txt` y `sitemap.xml` que es algo que no depende del lanzamiento del sitio redisenado.

**Comment by paco-leyva** [comment]
@huhgawz creo que el sitemap y las keywords podrían ser un agregado/cambio rápido. La verdad es que el SEO no es malo y la velocidad de carga es bueno entonces no hay tanto problema. Lo ideal sería también conseguir la mayor cantidad de menciones del sitio en redes sociales y páginas, pero bueno eso tal vez sea otra etapa. Saludos.

**Comment by huhgawz** [comment]
@paco-antley @marianagh cualquier otra sugerencia es bienvenida.

- El sitio efectivamente esta bajo HTTPS https://sismomexico.org
- El sitio cuenta con un favicon https://github.com/CodeandoMexico/terremoto-cdmx/blob/master/img/favicon.ico

Quizas sea buena idea esperar la liberacion del sitio redisenado para aplicar el resto de las sugerencias que hicieron

**Comment by tlacoyodefrijol** [comment]
@huhgawz ya está la versión nueva arriba. Si quieren avanzar con el SEO

**Comment by marianagh** [comment]
Desglosar esta actividad seria mas apropiado ya que es una mejora que involucra todo el sitio.

**Comment by gabelula** [comment]
Creo que estan todos los PRs relacionados a este issue.

**Comment by huhgawz** [comment]
@gabelula es correcto. Despues de mezclar #147 se puede cerrar este issue

**Comment by chinodf** [comment]
Te recomiendo este [curso de SEO](https://www.grupocodesi.com/cursos/curso-de-posicionamiento-seo.html). Seguramente te hace falta meter algunos buenos backlinks.
