### ISSUE TITLE
Asignar correctamente el dominio www.sismomexico.org

### ISSUE THREAD

**Issue by huhgawz** [CodeandoMexico/terremoto-cdmx#94]
Se han hecho varios intentos:  6725a41, #61, etc . Sin embargo, al acceder a http://www.sismomexico.org la URL cambia a https://codeandomexico.github.io/terremoto-cdmx. Asignar correctamente el dominio es importante por multiples razones: 1) para garantizar que en las redes sociales/chats/medios de comunicacion solo se difunda una unica URL del sitio (http://www.sismomexico.org), 2) mejorar el [SEO](https://en.wikipedia.org/wiki/Search_engine_optimization) del sitio (#93), etc.

**Comment by javierojeda94** [comment]
Se conoce el motivo por el cual el dominio no responde? No veo un archivo `CNAME` en el proyecto y por lo que tengo entendido Github necesita dicho archivo para mapear a un dominio.

Si no se resuelve intentaré echarles la mano esta noche

**Comment by magiabinaria** [comment]
El dominio ya responde, www.sismomexico.org ---> https://codeandomexico.github.io/terremoto-cdmx/

**Comment by javierojeda94** [comment]
entonces ese comportamiento (el redirect) es el esperado?

**Comment by huhgawz** [comment]
@magiabinaria @javierojeda94 en este issue lo que se busca, es que cuando un usuario acceda a http://www.sismomexico.org la URL persista; es decir, que no cambie a https://codeandomexico.github.io/terremoto-cdmx. De este modo, si un usuario una vez estando dentro del sitio, copia la URL del sitio, quizas con la intencion de compartirla/difundirla, comparta/difunda la URL oficial del sitio (http://www.sismomexico.org).

**Comment by javierbyte** [comment]
@huhgawz @javierojeda94 ya me encargo! confirmado que los DNS anterior han sido expirados, haré un anuncio en slack y cambiaré el dominio a que se mantenga en sismomexico.org

**Comment by javierbyte** [comment]
listo https://sismomexico.org/ https://mapa.sismomexico.org/

**Comment by javierojeda94** [comment]
Excelente @javierbyte !!!
